
import React, { createContext, useContext, useState, ReactNode } from 'react';

export type Language = 'en' | 'zh-TW' | 'zh-CN' | 'es';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
  font: string;
}

const translations: Record<Language, Record<string, string>> = {
  en: {
    'nav.home': 'Home',
    'nav.about': 'Our Mission',
    'nav.stories': 'Stories',
    'nav.resources': 'Resources',
    'nav.contact': 'Contact',
    'nav.chat': 'AI Support',
    'nav.login': 'Log in',
    'nav.join': 'Join Us',
    'nav.donate': 'Donate',
    'nav.profile': 'My Profile',
    'nav.signout': 'Sign Out',
    'nav.admin': 'Admin Dashboard',
    
    // Admin
    'admin.title': 'Admin Dashboard',
    'admin.tab.resources': 'Manage Resources',
    'admin.tab.stories': 'Manage Stories',
    'admin.add_resource': 'Add New Resource',
    'admin.add_story': 'Add New Story',
    'admin.edit_story': 'Edit Story',
    'admin.form.name': 'Organization Name',
    'admin.form.type': 'Service Type',
    'admin.form.region': 'Region',
    'admin.form.contact': 'Contact Phone',
    'admin.form.location': 'Address',
    'admin.form.desc': 'Description',
    'admin.story.title': 'Story Title',
    'admin.story.category': 'Category',
    'admin.story.type': 'Media Type',
    'admin.story.author': 'Author / Credit',
    'admin.story.media': 'Media URL',
    'admin.story.cover': 'Cover Image URL',
    'admin.story.date': 'Date',
    'admin.success': 'Operation Successful',
    'admin.delete': 'Delete',
    'admin.delete_confirm': 'Are you sure you want to delete this?',
    'admin.preview_mode': 'Preview Mode Active: Changes are local and will reset on refresh.',

    // Common
    'common.loading': 'Loading...',
    'common.back': 'Back',
    'common.submit': 'Submit',
    'common.processing': 'Processing...',
    'common.success': 'Success',
    'common.error': 'Error',
    'common.cancel': 'Cancel',
    'common.save': 'Save Changes',
    
    // Hero & Home General
    'hero.title': 'Amplifying Voices of the Overlooked',
    'hero.subtitle': 'We use documentary storytelling to surface lived experiences of homelessness, addiction, and hardship.',
    'hero.badge': 'Recording Reality',
    'hero.cta_stories': 'Watch Stories',
    'hero.cta_submit': 'Submit Story',
    'hero.cta_about': 'Learn About Us',
    'hero.cta_donate': 'Donate Now',
    'hero.change_photo': 'Change Photo',
    'hero.photo_source': 'Photo source',
    'hero.drop_zone': 'Drop Image to Change',

    // Impact Stats
    'home.impact.stories': 'Stories Told',
    'home.impact.helped': 'People Assisted',
    'home.impact.verified_shelters': 'Verified Shelters',
    'home.impact.partners': 'Agencies Linked',
    'home.impact.volunteers': 'Active Members',

    // News
    'home.news.title': 'California Crisis Updates',
    'home.news.subtitle': 'Live updates on social policy.',
    'home.news.loading': 'Fetching latest updates...',
    'home.news.generated': 'AI Summarized (Google Search)',
    'home.news.sources': 'Primary Sources',
    'home.news.error': 'Unable to load news.',

    // Methodology / Pillars
    'home.methodology.tag': 'Our Methodology',
    'home.methodology.title': 'Bridging Empathy & Action',
    'home.pillar1.title': 'Documentary Journalism',
    'home.pillar1.desc': 'Unveiling truth through raw, unfiltered imagery.',
    'home.pillar2.title': 'Immediate Action',
    'home.pillar2.desc': 'Directly linking narratives to 70+ verified agencies.',
    'home.pillar3.title': 'Policy Advocacy',
    'home.pillar3.desc': 'Driving systemic change with visual evidence.',

    // Stories Page
    'stories.header.tag': 'Documentary Archives',
    'stories.header.title': 'Community Stories',
    'stories.header.sub': 'Authentic narratives captured by our teams to bridge the gap between empathy and action.',
    'stories.tab.video': 'Video',
    'stories.tab.photo': 'Photo',
    'stories.tab.audio': 'Podcast / Audio',
    'stories.filter.all': 'All',
    'stories.btn.submit': 'Share Your Story',
    'stories.empty': 'No stories found in this category.',
    'stories.modal.resource_btn': 'Find Support Resources',

    // Submit Story Page
    'submit.title': 'Contribute to the Archive',
    'submit.subtitle': 'Your perspective matters. Upload photos, videos, or audio interviews to document reality.',
    'submit.type.video_photo': 'Visual (Video/Photo)',
    'submit.type.audio': 'Audio (Podcast/Interview)',
    'submit.upload_photo': 'Upload Photos',
    'submit.upload_video': 'Upload Video',
    'submit.upload_audio': 'Upload Audio File',
    'submit.upload_cover': 'Cover Image (Optional)',
    'submit.form.title': 'Story Title',
    'submit.form.location': 'Location (City/Street)',
    'submit.form.category': 'Category',
    'submit.form.desc': 'The Narrative',
    'submit.form.desc_placeholder': 'Describe the context, the people, and the moment...',
    'submit.terms': 'I certify that I have the right to share this content and grant Voice Through Image permission to use it for non-profit educational purposes.',
    'submit.success_title': 'Narrative Archived',
    'submit.success_desc': 'Your submission has been securely uploaded to our database. Thank you for being a witness.',

    // Resources Page
    'resources.hero.tag': 'AI Resource Assistant',
    'resources.hero.title': 'How can we help you today?',
    'resources.hero.sub': 'Search for resources using natural language. We\'ll connect you with verified services.',
    'resources.search.placeholder': 'Ex: I need a safe place to sleep in Los Angeles...',
    'resources.search.btn': 'Search',
    'resources.prompt.shelter': 'Find Shelters',
    'resources.prompt.legal': 'Legal Aid',
    'resources.prompt.food': 'Free Food',
    'resources.prompt.mental': 'Mental Health',
    'resources.directory.title': 'Browse Directory',
    'resources.directory.sub': 'Select a category to view verified organizations.',
    'resources.directory.search_placeholder': 'Search by name, city, or service...',
    'resources.directory.view_all': 'View All Categories',
    'resources.ai_result': 'Assistant Response',
    'resources.close': 'Close',

    // Resource Categories
    'resources.title': 'Support Resources',
    'resources.subtitle': 'Find verified local support.',
    'resources.cat.shelter': 'Emergency Shelters',
    'resources.cat.food': 'Food Banks',
    'resources.cat.legal': 'Legal Aid',
    'resources.cat.mental_health': 'Mental Health',
    'resources.cat.dv': 'Domestic Violence',
    'resources.cat.chinese_services': 'Chinese Speaking Support',
    'resources.cat.recovery': 'Addiction Recovery',

    // About Page
    'about.title': 'Our Collective Purpose',
    'about.subtitle': 'A non-profit documentary platform humanizing social crises through visual journalism.',
    'about.tag': 'Our Core Identity',
    'about.vision_title': 'Vision & Legacy',
    'about.vision_sub': 'OUR VISION',
    'about.vision_text': '"To bridge the gap between social invisibility and active empathy through the power of raw, honest imagery."',
    'about.mission_sub': 'OUR MISSION',
    'about.mission_1': 'Document the unvarnished reality of homelessness and addiction with dignity.',
    'about.mission_2': 'Bridge marginalized individuals with immediate, culturally-sensitive resources.',
    'about.mission_3': 'Drive social policy change through evidence-based visual advocacy.',
    'about.participate.title': 'How You Can Participate',
    'about.participate.step1': 'Witness',
    'about.participate.step1_desc': 'Engage with our narratives and understand the systemic issues.',
    'about.participate.step2': 'Join',
    'about.participate.step2_desc': 'Register as a volunteer or contributor in your local city.',
    'about.participate.step3': 'Submit',
    'about.participate.step3_desc': 'Help us find the stories that need to be told.',
    'about.volunteer.title': 'Volunteer With Us',
    'about.volunteer.desc': 'Join our compassionate team of field documentarians, outreach coordinators, and administrative support. Your time can change lives.',
    'about.volunteer.roles': 'Roles: Field Documentation, Community Outreach, Event Support, Translation Services.',
    'about.volunteer.btn': 'Sign Up to Volunteer',
    
    // Contact Page
    'contact.tag': 'Get in Touch',
    'contact.title': 'Contact Us',
    'contact.subtitle': 'We are here to listen, support, and collaborate. Reach out to our team.',
    'contact.office': 'Headquarters',
    'contact.email': 'Email Us',
    'contact.phone': 'Call Us',
    'contact.office_hours': 'Mon-Fri, 9am - 5pm PST',
    'contact.form.title': 'Send a Message',
    'contact.form.name': 'Full Name',
    'contact.form.email': 'Email Address',
    'contact.form.subject': 'Subject',
    'contact.form.message': 'Message',
    'contact.form.send': 'Send Message',

    // Volunteer Page
    'volunteer.title': 'Join Our Mission',
    'volunteer.subtitle': 'Lend your skills to amplify voices and support our community operations.',
    'volunteer.form.name': 'Full Name',
    'volunteer.form.email': 'Email Address',
    'volunteer.form.phone': 'Phone Number',
    'volunteer.form.role': 'Area of Interest',
    'volunteer.form.message': 'Why do you want to volunteer?',
    'volunteer.success': 'Thank you! Your application has been received.',
    
    // Donate Page
    'donate.page.title': 'Fund the Mission',
    'donate.page.sub': 'Your support helps us stay on the ground, personally helping those in need and filming stories that inspire hope.',
    'donate.tiers.title': 'Direct Action & Positive Impact',
    'donate.tier1.title': 'Field Documentation',
    'donate.tier1.desc': 'We need equipment to stay on the ground, capturing authentic stories of resilience. We are there personally to witness and record the truth.',
    'donate.tier2.title': 'Hands-On Community Aid',
    'donate.tier2.desc': 'We don’t just watch; we act. We personally deliver essential supplies, coordinate shelter, and provide human connection to those ignored by society.',
    'donate.tier3.title': 'Stories of Hope',
    'donate.tier3.desc': 'We produce high-quality documentaries that focus on human potential and positive transformation, proving that everyone deserves a second chance.',
    'donate.secure': 'Secure Payment via Zeffy',
    'donate.fee_note': '100% of your donation goes to us. Zeffy covers the fees.',
    'donate.check': 'To donate by check or stock, please contact us.',
    'about.donate.title': 'Empower the Narrative',
    'about.donate.subtitle': 'Your contribution enables us to produce high-quality documentaries that drive real policy change.',
    'about.donate.tax': 'Donations are 100% Tax-Deductible',
    'about.donate.btn': 'Donate Now',

    // NEW 20-SLIDE PRESENTATION
    'pres.s1.title': 'Voice Through Image',
    'pres.s1.sub': 'A Tech-Driven Humanitarian Platform',
    'pres.s1.tag': 'Est. 2025',
    'pres.s2.title': 'The Disconnection',
    'pres.s2.text': 'Resources Exist, Connection Fails',
    'pres.s2.sub': 'Empathy fatigue + scattered information = inaction.',
    'pres.s2.p1': 'Fragmented Aid Systems',
    'pres.s2.p2': 'Public "Compassion Fatigue"',
    'pres.s2.p3': 'No Clear Path to Help',
    'pres.s3.title': 'Our Core Philosophy',
    'pres.s3.vis': 'Action Over Pity',
    'pres.s3.mis': 'We do not film "misery" to generate guilt. We document reality to trigger immediate, tangible intervention.',
    'pres.s4.title': 'The Solution Ecosystem',
    'pres.s4.p1': 'Documentary',
    'pres.s4.d1': 'Visual Evidence',
    'pres.s4.p2': 'AI Platform',
    'pres.s4.d2': 'Smart Integration',
    'pres.s4.p3': 'Community',
    'pres.s4.d3': 'Direct Action',
    'pres.s5.title': 'Advanced Technology',
    'pres.s5.stat': '24/7',
    'pres.s5.desc': 'Gemini AI Integration',
    'pres.s5.text': 'Our platform uses Google Gemini AI to provide real-time, 24/7 resource matching for those in crisis.',
    'pres.s6.title': 'The Digital Hub',
    'pres.s6.sub': 'Unified Resource Database',
    'pres.s6.p1': '70+ Verified Agencies',
    'pres.s6.p2': 'Live Map Data',
    'pres.s6.p3': 'Instant Navigation',
    'pres.s7.title': 'Democratized Storytelling',
    'pres.s7.sub': 'Public Upload Feature',
    'pres.s7.p1': 'Anyone Can Contribute',
    'pres.s7.p2': 'Verified by VTI Team',
    'pres.s7.p3': 'Voices from the Ground',
    'pres.s8.title': 'User Journey',
    'pres.s8.steps': '1. Witness Story -> 2. Feel Empathy -> 3. AI Matches Resource -> 4. Direct Action',
    'pres.s9.title': 'Dignity First',
    'pres.s9.text': 'We empower subjects to tell their OWN stories.',
    'pres.s9.sub': 'No exploitation. Only empowerment.',
    'pres.s10.title': 'Impact Metrics',
    'pres.s10.stat1': '850+ Helped',
    'pres.s10.stat2': '120 Stories',
    'pres.s10.stat3': '45 Volunteers',
    'pres.s11.title': 'Real Success',
    'pres.s11.quote': 'The AI bot found me a shelter at 3 AM when no one else answered.',
    'pres.s11.author': 'Sarah, Beneficiary',
    'pres.s12.title': 'Competitive Advantage',
    'pres.s12.us': 'VTI Tech Model',
    'pres.s12.others': 'Traditional Non-Profits',
    'pres.s12.p1': 'AI-Driven Speed',
    'pres.s12.o1': 'Slow Manual Intake',
    'pres.s12.p2': 'Visual Transparency',
    'pres.s12.o2': 'Annual PDF Reports',
    'pres.s13.title': 'Tech Stack',
    'pres.s13.stack': 'React + Firebase + Google Cloud AI',
    'pres.s13.desc': 'Built for scale, speed, and reliability.',
    'pres.s14.title': 'Scalability',
    'pres.s14.text': 'Our model is city-agnostic. We launch in LA, then expand globally.',
    'pres.s15.title': 'Financial Transparency',
    'pres.s15.sub': 'Where investment goes',
    'pres.s15.p1': 'Tech Development',
    'pres.s15.p2': 'Field Ops',
    'pres.s15.p3': 'Admin',
    'pres.s16.title': 'Roadmap 2026',
    'pres.s16.q1': 'Mobile App Launch',
    'pres.s16.q2': 'San Diego Expansion',
    'pres.s16.q3': 'National Partner Network',
    'pres.s17.title': 'Official Status',
    'pres.s17.stat': '501(c)(3)',
    'pres.s17.text': 'Fully tax-deductible donations. IRS Certified.',
    'pres.s18.title': 'The Ask',
    'pres.s18.goal': '$500k',
    'pres.s18.sub': 'Seed Funding for 18 Months',
    'pres.s18.items': 'Dev Team, Van, Camera Gear, Outreach Staff',
    'pres.s19.title': 'Why Now?',
    'pres.s19.text': 'The crisis is peaking. Technology is ready. We are ready.',
    'pres.s20.title': 'Join the Movement',
    'pres.s20.sub': 'Invest in Action.',
    'pres.s20.cta': 'Donate / Partner',

    // Footer & Legal
    'about.history': 'Corporate History',
    'about.history_text': 'Founded in late 2025, Voice Through Image was established to counter the rising "compassion fatigue" in major urban centers.',
    'about.leadership': 'Leadership',
    'about.founder': 'FOUNDER & CEO',
    'about.roles': 'BOARD ROLES',
    'about.roles_list': 'Legal Compliance, Narrative Strategy, Community Outreach.',
    'about.legal': 'Non-Profit Status',
    'about.legal_text': 'Voice Through Image is a registered 501(c)(3) tax-exempt organization. Donations are tax-deductible to the full extent of the law.',
    'about.legal_ein': 'FEDERAL EIN',
    'footer.desc': 'A non-profit documentary platform dedicated to humanizing social crises.',
    'footer.ein': 'EIN: 41-2510011',
    'footer.tax_exempt': 'IRS Determined 501(c)(3)',
    'footer.governance': 'Governance',
    'footer.links.irs': 'IRS Determination Letter',
    'footer.links.financial': 'Financial Reports',
    'footer.links.bylaws': 'Bylaws & Policies',
    'footer.links.deck': 'View Official Deck',
    'footer.rights': 'All Rights Reserved.',
    'footer.privacy': 'Privacy Policy',
    'footer.terms': 'Terms of Service',

    // Chat
    'chat.welcome': 'Welcome to Voice Through Image Support. How can I help you today?',
    'chat.placeholder': 'Ask about resources, our mission, or get support...',
    'chat.send': 'Send Message',
    'chat.disclaimer': 'I am an AI assistant. For emergencies, please call 911 immediately.',
    'chat.error': 'Connection lost. Please try again later.',
    
    // Auth
    'auth.login.title': 'Welcome Back',
    'auth.login.subtitle': 'Sign in to access your account',
    'auth.login.btn': 'Sign In',
    'auth.signup.title': 'Create Account',
    'auth.signup.subtitle': 'Join our community of changemakers',
    'auth.signup.btn': 'Create Account',
    'auth.verify.title': 'Verify your email',
    'auth.verify.text': 'We sent a verification link to',
    'profile.title': 'My Profile',
    'profile.manage': 'Manage your account settings',
    'profile.edit': 'Edit Profile',
    'profile.save': 'Save Changes',
  },
  'zh-TW': {
    'nav.home': '首頁',
    'nav.about': '我們的使命',
    'nav.stories': '故事',
    'nav.resources': '資源',
    'nav.contact': '聯絡我們',
    'nav.chat': 'AI 助手',
    'nav.login': '登入',
    'nav.join': '加入我們',
    'nav.donate': '捐款',
    'nav.profile': '個人檔案',
    'nav.signout': '登出',
    'nav.admin': '管理者後台',

    // Admin
    'admin.title': '管理者後台',
    'admin.tab.resources': '管理資源',
    'admin.tab.stories': '管理故事',
    'admin.add_resource': '新增資源機構',
    'admin.add_story': '新增故事',
    'admin.edit_story': '編輯故事',
    'admin.form.name': '機構名稱',
    'admin.form.type': '服務類別',
    'admin.form.region': '地區',
    'admin.form.contact': '聯絡電話',
    'admin.form.location': '地址',
    'admin.form.desc': '描述',
    'admin.story.title': '故事標題',
    'admin.story.category': '分類',
    'admin.story.type': '媒體類型',
    'admin.story.author': '作者 / 來源',
    'admin.story.media': '媒體連結 (影片/音檔)',
    'admin.story.cover': '封面圖片連結',
    'admin.story.date': '日期',
    'admin.success': '操作成功',
    'admin.delete': '刪除',
    'admin.delete_confirm': '確定要刪除此項目嗎？',
    'admin.preview_mode': '預覽模式：變更僅暫存於瀏覽器，重整後將還原。',
    
    'common.loading': '載入中...',
    'common.back': '返回',
    'common.submit': '提交',
    'common.processing': '處理中...',
    'common.success': '成功',
    'common.error': '錯誤',
    'common.cancel': '取消',
    'common.save': '儲存變更',

    // Hero & Home
    'hero.title': '放大被忽視的聲音',
    'hero.subtitle': '我們透過紀錄片敘事呈現真實經歷——將觀眾與實際支援連結起來。',
    'hero.badge': '記錄真實',
    'hero.cta_stories': '觀看故事',
    'hero.cta_submit': '提交故事',
    'hero.cta_about': '了解我們',
    'hero.cta_donate': '立即捐款',
    'hero.change_photo': '更換照片',
    'hero.photo_source': '圖片來源',
    'hero.drop_zone': '拖放以更換圖片',

    'home.impact.stories': '已說故事',
    'home.impact.helped': '已助人數',
    'home.impact.verified_shelters': '驗證收容所',
    'home.impact.partners': '機構連結',
    'home.impact.volunteers': '活躍志工',

    'home.news.title': '加州危機動態',
    'home.news.subtitle': '社會政策的實時更新。',
    'home.news.loading': '正在獲取最新動態...',
    'home.news.generated': 'AI 智慧摘要 (Google Search)',
    'home.news.sources': '新聞來源',
    'home.news.error': '無法載入新聞。',

    // Methodology
    'home.methodology.tag': '我們的方法論',
    'home.methodology.title': '連結同理心與行動',
    'home.pillar1.title': '紀實新聞學',
    'home.pillar1.desc': '透過原始、未經修飾的影像揭露真相。',
    'home.pillar2.title': '即時行動',
    'home.pillar2.desc': '將敘事直接連結至 70+ 個經過驗證的機構。',
    'home.pillar3.title': '政策倡導',
    'home.pillar3.desc': '透過視覺證據推動系統性變革。',

    // Stories Page
    'stories.header.tag': '紀錄片檔案館',
    'stories.header.title': '社區故事',
    'stories.header.sub': '由我們團隊捕捉的真實敘事，旨在連結同理心與行動。',
    'stories.tab.video': '影片',
    'stories.tab.photo': '攝影',
    'stories.tab.audio': 'Podcast / 錄音',
    'stories.filter.all': '全部',
    'stories.btn.submit': '分享您的故事',
    'stories.empty': '此分類尚無故事。',
    'stories.modal.resource_btn': '尋找支援資源',

    // Submit Story Page
    'submit.title': '貢獻至檔案館',
    'submit.subtitle': '您的視角至關重要。上傳照片、影片或錄音訪談，記錄街道上的真實情況。',
    'submit.type.video_photo': '視覺影像 (影片/照片)',
    'submit.type.audio': '聲音採訪 (Podcast)',
    'submit.upload_photo': '上傳照片',
    'submit.upload_video': '上傳影片',
    'submit.upload_audio': '上傳音檔',
    'submit.upload_cover': '封面圖片 (選填)',
    'submit.form.title': '故事標題',
    'submit.form.location': '發生地點 (城市/街道)',
    'submit.form.category': '分類',
    'submit.form.desc': '敘事內容',
    'submit.form.desc_placeholder': '描述當下的情境、人物與時刻...',
    'submit.terms': '我保證擁有此內容的權利，並授權 Voice Through Image 用於非營利教育用途。',
    'submit.success_title': '敘事已歸檔',
    'submit.success_desc': '您的提交已安全上傳至我們的資料庫。感謝您成為見證者。',

    // Resources Page
    'resources.hero.tag': 'AI 資源助手',
    'resources.hero.title': '今天有什麼可以幫您的？',
    'resources.hero.sub': '使用自然語言搜尋資源。我們將為您連結經過驗證的服務。',
    'resources.search.placeholder': '例如：我需要在洛杉磯找一個安全的過夜處...',
    'resources.search.btn': '搜尋',
    'resources.prompt.shelter': '尋找收容所',
    'resources.prompt.legal': '法律援助',
    'resources.prompt.food': '食物發放',
    'resources.prompt.mental': '心理諮商',
    'resources.directory.title': '瀏覽目錄',
    'resources.directory.sub': '選擇一個類別以查看經過驗證的機構。',
    'resources.directory.search_placeholder': '搜尋名稱、城市或服務...',
    'resources.directory.view_all': '查看所有分類',
    'resources.ai_result': '助手回覆',
    'resources.close': '關閉',

    'resources.title': '支援資源',
    'resources.subtitle': '搜尋經過驗證的在地支援。',
    'resources.cat.shelter': '緊急收容所',
    'resources.cat.food': '食物銀行',
    'resources.cat.legal': '法律援助',
    'resources.cat.mental_health': '心理健康',
    'resources.cat.dv': '家庭暴力',
    'resources.cat.chinese_services': '華語專項服務',
    'resources.cat.recovery': '藥物成癮康復',

    // About Page
    'about.title': '我們的使命',
    'about.subtitle': '透過視覺紀實，將社會危機人性化的非營利平台。',
    'about.tag': '我們的核心身份',
    'about.vision_title': '願景與傳承',
    'about.vision_sub': '我們的願景',
    'about.vision_text': '「透過真實、誠實的影像力量，消除社會忽視與主動同理心之間的鴻溝。」',
    'about.mission_sub': '核心使命',
    'about.mission_1': '以尊嚴記錄無家可歸與成癮問題的真實現狀。',
    'about.mission_2': '為邊緣群體與即時的、具文化敏感性的資源建立橋樑。',
    'about.mission_3': '透過基於實證的視覺倡議，推動社會政策變革。',
    'about.participate.title': '如何參與',
    'about.participate.step1': '見證',
    'about.participate.step1_desc': '深入了解敘事，理解背後的系統性問題。',
    'about.participate.step2': '加入',
    'about.participate.step2_desc': '註冊成為志工，在您所在的城市貢獻力量。',
    'about.participate.step3': '提交',
    'about.participate.step3_desc': '幫助我們挖掘那些需要被聽見的故事。',
    'about.volunteer.title': '成為志工',
    'about.volunteer.desc': '加入我們充滿熱忱的團隊，包括田野紀實、社區外展及行政支援。您的時間可以改變生命。',
    'about.volunteer.roles': '角色：田野紀實、社區外展、活動支援、翻譯服務。',
    'about.volunteer.btn': '立即報名志工',
    
    // Contact Page
    'contact.tag': '保持聯繫',
    'contact.title': '聯絡我們',
    'contact.subtitle': '我們在這裡傾聽、支持並合作。請隨時聯繫我們的團隊。',
    'contact.office': '總部辦公室',
    'contact.email': '電子郵件',
    'contact.phone': '電話',
    'contact.office_hours': '週一至週五，上午9點至下午5點 (PST)',
    'contact.form.title': '發送訊息',
    'contact.form.name': '全名',
    'contact.form.email': '電子郵件',
    'contact.form.subject': '主旨',
    'contact.form.message': '訊息內容',
    'contact.form.send': '發送訊息',

    // Volunteer Page
    'volunteer.title': '加入我們的使命',
    'volunteer.subtitle': '貢獻您的專長，放大被忽視的聲音並支援我們的社區運作。',
    'volunteer.form.name': '全名',
    'volunteer.form.email': '電子郵件',
    'volunteer.form.phone': '電話號碼',
    'volunteer.form.role': '感興趣的領域',
    'volunteer.form.message': '為什麼您想成為志工？',
    'volunteer.success': '感謝您！我們已收到您的申請。',
    
    // Donate Page
    'donate.page.title': '資助我們的使命',
    'donate.page.sub': '您的支持將協助我們親自在現場，幫助需要的人，並拍攝傳遞希望的真實故事。',
    'donate.tiers.title': '直接行動與正面影響',
    'donate.tier1.title': '田野紀實裝備',
    'donate.tier1.desc': '我們需要器材支援以深入現場，捕捉堅韌的生命故事。我們親自在場，見證並記錄真實。',
    'donate.tier2.title': '親力親為的社區援助',
    'donate.tier2.desc': '我們不只是旁觀，更付諸行動。我們親手發放物資、協調收容，為被社會忽視的人們提供即時關懷與連結。',
    'donate.tier3.title': '傳遞希望的影像',
    'donate.tier3.desc': '我們製作聚焦於正面轉變與人性潛能的紀錄片，向世界證明：每個人都值得一個重生的機會。',
    'donate.secure': '透過 Zeffy 安全支付',
    'donate.fee_note': '您的捐款將 100% 交給我們。Zeffy 平台自行吸收手續費。',
    'donate.check': '如需透過支票或股票捐款，請聯繫我們。',
    'about.donate.title': '賦予敘事力量',
    'about.donate.subtitle': '您的捐款將直接支持我們製作推動政策改變的高品質紀錄片。',
    'about.donate.tax': '捐款可 100% 抵扣稅款',
    'about.donate.btn': '立即捐款',

    // NEW 20-SLIDE PRESENTATION
    'pres.s1.title': '影像之聲 VTI',
    'pres.s1.sub': '科技驅動的人道主義平台',
    'pres.s1.tag': '成立於 2025',
    'pres.s2.title': '斷裂的連結',
    'pres.s2.text': '資源存在，但連結失效',
    'pres.s2.sub': '同理心疲勞 + 資訊分散 = 行動停滯。',
    'pres.s2.p1': '援助體系碎片化',
    'pres.s2.p2': '大眾對苦難麻木',
    'pres.s2.p3': '缺乏求助路徑',
    'pres.s3.title': '我們的核心理念',
    'pres.s3.vis': '行動重於憐憫',
    'pres.s3.mis': '我們拍攝的目的不是為了「販賣悲慘」或製造內疚，而是為了記錄真實，並觸發即時、有形的干預行動。',
    'pres.s4.title': '解決方案生態系',
    'pres.s4.p1': '紀錄片',
    'pres.s4.d1': '視覺證據',
    'pres.s4.p2': 'AI 平台',
    'pres.s4.d2': '智慧整合',
    'pres.s4.p3': '社區',
    'pres.s4.d3': '直接行動',
    'pres.s5.title': '先進科技應用',
    'pres.s5.stat': '24/7',
    'pres.s5.desc': 'Gemini AI 整合',
    'pres.s5.text': '我們的平台利用 Google Gemini AI，為處於危機中的人們提供全天候、即時的資源配對。',
    'pres.s6.title': '數位樞紐',
    'pres.s6.sub': '統一資源資料庫',
    'pres.s6.p1': '70+ 驗證機構',
    'pres.s6.p2': '即時地圖數據',
    'pres.s6.p3': '一鍵導航',
    'pres.s7.title': '敘事民主化',
    'pres.s7.sub': '公眾上傳功能',
    'pres.s7.p1': '全民參與記錄',
    'pres.s7.p2': 'VTI 團隊驗證',
    'pres.s7.p3': '來自現場的聲音',
    'pres.s8.title': '用戶旅程',
    'pres.s8.steps': '1. 目擊故事 -> 2. 產生共鳴 -> 3. AI 配對資源 -> 4. 直接行動',
    'pres.s9.title': '尊嚴至上',
    'pres.s9.text': '我們賦權被拍攝者講述「自己」的故事。',
    'pres.s9.sub': '拒絕剝削，只要賦權。',
    'pres.s10.title': '影響力數據',
    'pres.s10.stat1': '850+ 受助者',
    'pres.s10.stat2': '120 則故事',
    'pres.s10.stat3': '45 位志工',
    'pres.s11.title': '真實案例',
    'pres.s11.quote': '凌晨三點沒有人接電話，是 VTI 的 AI 幫我找到了開放的收容所。',
    'pres.s11.author': 'Sarah, 受助者',
    'pres.s12.title': '競爭優勢',
    'pres.s12.us': 'VTI 科技模式',
    'pres.s12.others': '傳統非營利',
    'pres.s12.p1': 'AI 驅動速度',
    'pres.s12.o1': '人工處理緩慢',
    'pres.s12.p2': '視覺透明化',
    'pres.s12.o2': '年度紙本報告',
    'pres.s13.title': '技術架構',
    'pres.s13.stack': 'React + Firebase + Google Cloud AI',
    'pres.s13.desc': '為規模化、速度與可靠性而生。',
    'pres.s14.title': '可擴展性',
    'pres.s14.text': '我們的模式不限城市。從洛杉磯出發，擴展至全球。',
    'pres.s15.title': '財務透明',
    'pres.s15.sub': '資金去向',
    'pres.s15.p1': '技術開發',
    'pres.s15.p2': '田野行動',
    'pres.s15.p3': '行政運作',
    'pres.s16.title': '2026 路線圖',
    'pres.s16.q1': '發布行動 App',
    'pres.s16.q2': '擴展至聖地牙哥',
    'pres.s16.q3': '建立全國夥伴網絡',
    'pres.s17.title': '官方地位',
    'pres.s17.stat': '501(c)(3)',
    'pres.s17.text': '美國國稅局認證，捐款可全額抵稅。',
    'pres.s18.title': '募資目標',
    'pres.s18.goal': '$500k',
    'pres.s18.sub': '18 個月的種子資金',
    'pres.s18.items': '開發團隊、外展車輛、攝影器材、全職人員',
    'pres.s19.title': '為何是現在？',
    'pres.s19.text': '危機已達頂峰，科技已經就緒。我們準備好了。',
    'pres.s20.title': '加入這場運動',
    'pres.s20.sub': '投資於行動。',
    'pres.s20.cta': '捐款 / 合作',

    // Footer & Legal
    'about.history': '機構歷史',
    'about.history_text': '成立於 2025 年底，Voice Through Image 旨在應對大都市日益嚴重的「同理心疲勞」。',
    'about.leadership': '領導團隊',
    'about.founder': '創辦人與執行長',
    'about.roles': '董事職務',
    'about.roles_list': '法律合規、敘事策略、社區外展。',
    'about.legal': '非營利組織地位',
    'about.legal_text': 'Voice Through Image 是註冊的 501(c)(3) 免稅組織。捐款依法可抵扣稅款。',
    'about.legal_ein': '聯邦統編 EIN',
    'footer.desc': '致力於將當代社會危機人性化的非營利紀錄片平台。',
    'footer.ein': 'EIN 統編: 41-2510011',
    'footer.tax_exempt': 'IRS 認定 501(c)(3) 免稅機構',
    'footer.governance': '治理與合規',
    'footer.links.irs': 'IRS 認定信函',
    'footer.links.financial': '財務報告',
    'footer.links.bylaws': '章程與政策',
    'footer.links.deck': '查看官方簡報',
    'footer.rights': '版權所有',
    'footer.privacy': '隱私政策',
    'footer.terms': '服務條款',

    // Chat
    'chat.welcome': '歡迎來到 Voice Through Image 支援中心。請問今天有什麼我可以幫您的？',
    'chat.placeholder': '詢問資源、了解我們的使命，或尋求支持...',
    'chat.send': '發送訊息',
    'chat.disclaimer': '我是 AI 助手。如遇緊急危險情況，請立即撥打 911。',
    'chat.error': '連線中斷，請稍後再試。',
    
    // Auth
    'auth.login.title': '歡迎回來',
    'auth.login.subtitle': '登入以存取您的帳戶',
    'auth.login.btn': '登入',
    'auth.signup.title': '建立帳戶',
    'auth.signup.subtitle': '加入我們的改革者社群',
    'auth.signup.btn': '建立帳戶',
    'auth.verify.title': '驗證您的電子郵件',
    'auth.verify.text': '我們已發送驗證連結至',
    'profile.title': '個人檔案',
    'profile.manage': '管理您的帳戶設定',
    'profile.edit': '編輯檔案',
    'profile.save': '儲存變更',
  },
  'zh-CN': {
    'nav.home': '首页',
    'nav.about': '我们的使命',
    'nav.stories': '故事',
    'nav.resources': '资源',
    'nav.contact': '联系我们',
    'nav.chat': 'AI 助手',
    'nav.login': '登录',
    'nav.join': '加入我们',
    'nav.donate': '捐款',
    'nav.profile': '个人档案',
    'nav.signout': '退出',
    'nav.admin': '管理员后台',

    // Admin
    'admin.title': '管理员后台',
    'admin.tab.resources': '管理资源',
    'admin.tab.stories': '管理故事',
    'admin.add_resource': '新增资源机构',
    'admin.add_story': '新增故事',
    'admin.edit_story': '编辑故事',
    'admin.form.name': '机构名称',
    'admin.form.type': '服务类别',
    'admin.form.region': '地区',
    'admin.form.contact': '联系电话',
    'admin.form.location': '地址',
    'admin.form.desc': '描述',
    'admin.story.title': '故事标题',
    'admin.story.category': '分类',
    'admin.story.type': '媒体类型',
    'admin.story.author': '作者 / 来源',
    'admin.story.media': '媒体链接 (视频/音频)',
    'admin.story.cover': '封面图片链接',
    'admin.story.date': '日期',
    'admin.success': '操作成功',
    'admin.delete': '删除',
    'admin.delete_confirm': '确定要删除此项目吗？',
    'admin.preview_mode': '预览模式：变更仅暂存于浏览器，刷新后将还原。',
    
    'common.loading': '加载中...',
    'common.back': '返回',
    'common.submit': '提交',
    'common.processing': '处理中...',
    'common.success': '成功',
    'common.error': '错误',
    'common.cancel': '取消',
    'common.save': '保存更改',

    // Hero & Home
    'hero.title': '放大被忽视的声音',
    'hero.subtitle': '我们通过纪录片叙事呈现真实经历——将观众与实际支援连接起来。',
    'hero.badge': '记录真实',
    'hero.cta_stories': '观看故事',
    'hero.cta_submit': '提交故事',
    'hero.cta_about': '了解我们',
    'hero.cta_donate': '立即捐款',
    'hero.change_photo': '更换照片',
    'hero.photo_source': '图片来源',
    'hero.drop_zone': '拖放以更换图片',

    'home.impact.stories': '已说故事',
    'home.impact.helped': '已助人数',
    'home.impact.verified_shelters': '验证收容所',
    'home.impact.partners': '机构链接',
    'home.impact.volunteers': '活跃志愿者',

    'home.news.title': '加州危机动态',
    'home.news.subtitle': '社会政策的实时更新。',
    'home.news.loading': '正在获取最新动态...',
    'home.news.generated': 'AI 智能摘要 (Google Search)',
    'home.news.sources': '新闻来源',
    'home.news.error': '无法加载新闻。',

    // Methodology
    'home.methodology.tag': '我们的方法论',
    'home.methodology.title': '连接同理心与行动',
    'home.pillar1.title': '纪实新闻学',
    'home.pillar1.desc': '通过原始、未经修饰的影像揭露真相。',
    'home.pillar2.title': '即时行动',
    'home.pillar2.desc': '将叙事直接连接至 70+ 个经过验证的机构。',
    'home.pillar3.title': '政策倡导',
    'home.pillar3.desc': '通过视觉证据推动系统性变革。',

    // Stories Page
    'stories.header.tag': '纪录片档案馆',
    'stories.header.title': '社区故事',
    'stories.header.sub': '由我们团队捕捉的真实叙事，旨在连接同理心与行动。',
    'stories.tab.video': '视频',
    'stories.tab.photo': '摄影',
    'stories.tab.audio': 'Podcast / 录音',
    'stories.filter.all': '全部',
    'stories.btn.submit': '分享您的故事',
    'stories.empty': '此分类尚无故事。',
    'stories.modal.resource_btn': '寻找支援资源',

    // Submit Story Page
    'submit.title': '贡献至档案馆',
    'submit.subtitle': '您的视角至关重要。上传照片、视频或录音访谈，记录街道上的真实情况。',
    'submit.type.video_photo': '视觉影像 (视频/照片)',
    'submit.type.audio': '声音采访 (Podcast)',
    'submit.upload_photo': '上传照片',
    'submit.upload_video': '上传视频',
    'submit.upload_audio': '上传音频',
    'submit.upload_cover': '封面图片 (选填)',
    'submit.form.title': '故事标题',
    'submit.form.location': '发生地点 (城市/街道)',
    'submit.form.category': '分类',
    'submit.form.desc': '叙事内容',
    'submit.form.desc_placeholder': '描述当下的情境、人物与时刻...',
    'submit.terms': '我保证拥有此内容的权利，并授权 Voice Through Image 用于非营利教育用途。',
    'submit.success_title': '叙事已归档',
    'submit.success_desc': '您的提交已安全上传至我们的数据库。感谢您成为见证者。',

    // Resources Page
    'resources.hero.tag': 'AI 资源助手',
    'resources.hero.title': '今天有什么可以帮您的？',
    'resources.hero.sub': '使用自然语言搜索资源。我们将为您连接经过验证的服务。',
    'resources.search.placeholder': '例如：我需要在洛杉矶找一个安全的过夜处...',
    'resources.search.btn': '搜索',
    'resources.prompt.shelter': '寻找收容所',
    'resources.prompt.legal': '法律援助',
    'resources.prompt.food': '食物发放',
    'resources.prompt.mental': '心理咨询',
    'resources.directory.title': '浏览目录',
    'resources.directory.sub': '选择一个类别以查看经过验证的机构。',
    'resources.directory.search_placeholder': '搜索名称、城市或服务...',
    'resources.directory.view_all': '查看所有分类',
    'resources.ai_result': '助手回复',
    'resources.close': '关闭',

    'resources.title': '支援资源',
    'resources.subtitle': '搜索经过验证的在地支援。',
    'resources.cat.shelter': '紧急收容所',
    'resources.cat.food': '食物银行',
    'resources.cat.legal': '法律援助',
    'resources.cat.mental_health': '心理健康',
    'resources.cat.dv': '家庭暴力',
    'resources.cat.chinese_services': '华语专项服务',
    'resources.cat.recovery': '药物成瘾康复',

    // About Page
    'about.title': '我们的使命',
    'about.subtitle': '通过视觉纪实，将社会危机人性化的非营利平台。',
    'about.tag': '我们的核心身份',
    'about.vision_title': '愿景与传承',
    'about.vision_sub': '我们的愿景',
    'about.vision_text': '「通过真实、诚实的影像力量，消除社会忽视与主动同理心之间的鸿沟。」',
    'about.mission_sub': '核心使命',
    'about.mission_1': '以尊严记录无家可归与成瘾问题的真实由状。',
    'about.mission_2': '为边缘群体与即时的、具文化敏感性的资源建立桥梁。',
    'about.mission_3': '通过基于实证的视觉倡议，推动社会政策变革。',
    'about.participate.title': '如何参与',
    'about.participate.step1': '见证',
    'about.participate.step1_desc': '深入了解叙事，理解背后的系统性问题。',
    'about.participate.step2': '加入',
    'about.participate.step2_desc': '注册成为志愿者，在您所在的城市贡献力量。',
    'about.participate.step3': '提交',
    'about.participate.step3_desc': '帮助我们挖掘那些需要被听见的故事。',
    'about.volunteer.title': '成为志愿者',
    'about.volunteer.desc': '加入我们充满热忱的团队，包括田野纪实、社区外展及行政支援。您的时间可以改变生命。',
    'about.volunteer.roles': '角色：田野纪实、社区外展、活动支援、翻译服务。',
    'about.volunteer.btn': '立即报名志愿者',
    
    // Contact Page
    'contact.tag': '保持联系',
    'contact.title': '联系我们',
    'contact.subtitle': '我们在这里倾听、支持并合作。请随时联系我们的团队。',
    'contact.office': '总部办公室',
    'contact.email': '电子邮件',
    'contact.phone': '电话',
    'contact.office_hours': '周一至周五，上午9点至下午5点 (PST)',
    'contact.form.title': '发送信息',
    'contact.form.name': '全名',
    'contact.form.email': '电子邮件',
    'contact.form.subject': '主题',
    'contact.form.message': '信息内容',
    'contact.form.send': '发送信息',

    // Volunteer Page
    'volunteer.title': '加入我们的使命',
    'volunteer.subtitle': '贡献您的专长，放大被忽视的声音并支援我们的社区运作。',
    'volunteer.form.name': '全名',
    'volunteer.form.email': '电子邮件',
    'volunteer.form.phone': '电话号码',
    'volunteer.form.role': '感兴趣的领域',
    'volunteer.form.message': '为什么您想成为志愿者？',
    'volunteer.success': '感谢您！我们已收到您的申请。',
    
    // Donate Page
    'donate.page.title': '资助我们的使命',
    'donate.page.sub': '您的支持将协助我们亲自在现场，帮助需要的人，并拍摄传递希望的真实故事。',
    'donate.tiers.title': '直接行动与正面影响',
    'donate.tier1.title': '田野纪实装备',
    'donate.tier1.desc': '我们需要器材支援以深入现场，捕捉坚韧的生命故事。我们亲自在场，见证并记录真实。',
    'donate.tier2.title': '亲力亲为的社区援助',
    'donate.tier2.desc': '我们不只是旁观，更付诸行动。我们亲手发放物资、协调收容，为被社会忽视的人们提供即时关怀与链接。',
    'donate.tier3.title': '传递希望的影像',
    'donate.tier3.desc': '我们制作聚焦于正面转变与人性潜能的纪录片，向世界证明：每个人都值得一个重生的机会。',
    'donate.secure': '通过 Zeffy 安全支付',
    'donate.fee_note': '您的捐款将 100% 交给我们。Zeffy 平台自行吸收手续费。',
    'donate.check': '如需通过支票或股票捐款，请联系我们。',
    'about.donate.title': '赋予叙事力量',
    'about.donate.subtitle': '您的捐款将直接支持我们制作推动政策改变的高质量纪录片。',
    'about.donate.tax': '捐款可 100% 抵扣税款',
    'about.donate.btn': '立即捐款',

    // NEW 20-SLIDE PRESENTATION
    'pres.s1.title': '影像之声 VTI',
    'pres.s1.sub': '科技驱动的人道主义平台',
    'pres.s1.tag': '成立于 2025',
    'pres.s2.title': '断裂的链接',
    'pres.s2.text': '资源存在，但链接失效',
    'pres.s2.sub': '同理心疲劳 + 信息分散 = 行动停滞。',
    'pres.s2.p1': '援助体系碎片化',
    'pres.s2.p2': '大众对苦难麻木',
    'pres.s2.p3': '缺乏求助路径',
    'pres.s3.title': '我们的核心理念',
    'pres.s3.vis': '行动重于怜悯',
    'pres.s3.mis': '我们拍摄的目的不是为了「贩卖悲惨」或制造内疚，而是为了记录真实，并触发即时、有形的干预行动。',
    'pres.s4.title': '解决方案生态系',
    'pres.s4.p1': '纪录片',
    'pres.s4.d1': '视觉证据',
    'pres.s4.p2': 'AI 平台',
    'pres.s4.d2': '智慧整合',
    'pres.s4.p3': '社区',
    'pres.s4.d3': '直接行动',
    'pres.s5.title': '先进科技应用',
    'pres.s5.stat': '24/7',
    'pres.s5.desc': 'Gemini AI 整合',
    'pres.s5.text': '我们的平台利用 Google Gemini AI，为处于危机中的人们提供全天候、即时的资源配对。',
    'pres.s6.title': '数字枢纽',
    'pres.s6.sub': '统一资源数据库',
    'pres.s6.p1': '70+ 验证机构',
    'pres.s6.p2': '实时地图数据',
    'pres.s6.p3': '一键导航',
    'pres.s7.title': '叙事民主化',
    'pres.s7.sub': '公众上传功能',
    'pres.s7.p1': '全民参与记录',
    'pres.s7.p2': 'VTI 团队验证',
    'pres.s7.p3': '来自现场的声音',
    'pres.s8.title': '用户旅程',
    'pres.s8.steps': '1. 目击故事 -> 2. 产生共鸣 -> 3. AI 配对资源 -> 4. 直接行动',
    'pres.s9.title': '尊严至上',
    'pres.s9.text': '我们赋权被拍摄者讲述「自己」的故事。',
    'pres.s9.sub': '拒绝剥削，只要赋权。',
    'pres.s10.title': '影响力数据',
    'pres.s10.stat1': '850+ 受助者',
    'pres.s10.stat2': '120 则故事',
    'pres.s10.stat3': '45 位志愿者',
    'pres.s11.title': '真实案例',
    'pres.s11.quote': '凌晨三点没有人接电话，是 VTI 的 AI 帮我找到了开放的收容所。',
    'pres.s11.author': 'Sarah, 受助者',
    'pres.s12.title': '竞争优势',
    'pres.s12.us': 'VTI 科技模式',
    'pres.s12.others': '传统非营利',
    'pres.s12.p1': 'AI 驱动速度',
    'pres.s12.o1': '人工处理缓慢',
    'pres.s12.p2': '视觉透明化',
    'pres.s12.o2': '年度纸本报告',
    'pres.s13.title': '技术架构',
    'pres.s13.stack': 'React + Firebase + Google Cloud AI',
    'pres.s13.desc': '为规模化、速度与可靠性而生。',
    'pres.s14.title': '可扩展性',
    'pres.s14.text': '我们的模式不限城市。从洛杉矶出发，扩展至全球。',
    'pres.s15.title': '财务透明',
    'pres.s15.sub': '资金去向',
    'pres.s15.p1': '技术开发',
    'pres.s15.p2': '田野行动',
    'pres.s15.p3': '行政运作',
    'pres.s16.title': '2026 路线图',
    'pres.s16.q1': '发布行动 App',
    'pres.s16.q2': '扩展至圣地牙哥',
    'pres.s16.q3': '建立全国伙伴网络',
    'pres.s17.title': '官方地位',
    'pres.s17.stat': '501(c)(3)',
    'pres.s17.text': '美国国税局认证，捐款可全额抵税。',
    'pres.s18.title': '募资目标',
    'pres.s18.goal': '$500k',
    'pres.s18.sub': '18 个月的种子资金',
    'pres.s18.items': '开发团队、外展车辆、摄影器材、全职人员',
    'pres.s19.title': '为何是现在？',
    'pres.s19.text': '危机已达顶峰，科技已经就绪。我们准备好了。',
    'pres.s20.title': '加入这场运动',
    'pres.s20.sub': '投资于行动。',
    'pres.s20.cta': '捐款 / 合作',

    // Footer & Legal
    'about.history': '机构历史',
    'about.history_text': '成立于 2025 年底，Voice Through Image 旨在应对大都市日益严重的「同理心疲劳」。',
    'about.leadership': '领导团队',
    'about.founder': '创始人与执行长',
    'about.roles': '董事职务',
    'about.roles_list': '法律合规、叙事策略、社区外展。',
    'about.legal': '非营利组织地位',
    'about.legal_text': 'Voice Through Image 是注册的 501(c)(3) 免税组织。捐款依法可抵扣税款。',
    'about.legal_ein': '联邦统编 EIN',
    'footer.desc': '致力于将当代社会危机人性化的非营利纪录片平台。',
    'footer.ein': 'EIN 统编: 41-2510011',
    'footer.tax_exempt': 'IRS 认定 501(c)(3) 免税机构',
    'footer.governance': '治理与合规',
    'footer.links.irs': 'IRS 认定信函',
    'footer.links.financial': '财务报告',
    'footer.links.bylaws': '章程与政策',
    'footer.links.deck': '查看官方简报',
    'footer.rights': '版权所有',
    'footer.privacy': '隐私政策',
    'footer.terms': '服务条款',

    // Chat
    'chat.welcome': '欢迎来到 Voice Through Image 支援中心。请问今天有什么我可以帮您的？',
    'chat.placeholder': '询问资源、了解我们的使命，或寻求支持...',
    'chat.send': '发送信息',
    'chat.disclaimer': '我是 AI 助手。如遇紧急危险情况，请立即拨打 911。',
    'chat.error': '连线中断，请稍后再试。',
    
    // Auth
    'auth.login.title': '欢迎回来',
    'auth.login.subtitle': '登录以存取您的帐户',
    'auth.login.btn': '登录',
    'auth.signup.title': '建立帐户',
    'auth.signup.subtitle': '加入我们的改革者社群',
    'auth.signup.btn': '建立帐户',
    'auth.verify.title': '验证您的电子邮件',
    'auth.verify.text': '我们已发送验证链接至',
    'profile.title': '个人档案',
    'profile.manage': '管理您的帐户设定',
    'profile.edit': '编辑档案',
    'profile.save': '保存变更',
  },
  'es': {
    'nav.home': 'Inicio',
    'nav.about': 'Nuestra Misión',
    'nav.stories': 'Historias',
    'nav.resources': 'Recursos',
    'nav.contact': 'Contacto',
    'nav.chat': 'Asistente IA',
    'nav.login': 'Iniciar Sesión',
    'nav.join': 'Únete',
    'nav.donate': 'Donar',
    'nav.profile': 'Mi Perfil',
    'nav.signout': 'Cerrar Sesión',
    'nav.admin': 'Panel de Administración',
    
    // Admin
    'admin.title': 'Panel de Administración',
    'admin.tab.resources': 'Administrar Recursos',
    'admin.tab.stories': 'Administrar Historias',
    'admin.add_resource': 'Agregar Nuevo Recurso',
    'admin.add_story': 'Agregar Nueva Historia',
    'admin.edit_story': 'Editar Historia',
    'admin.form.name': 'Nombre de la Organización',
    'admin.form.type': 'Tipo de Servicio',
    'admin.form.region': 'Región',
    'admin.form.contact': 'Teléfono de Contacto',
    'admin.form.location': 'Dirección',
    'admin.form.desc': 'Descripción',
    'admin.story.title': 'Título de la Historia',
    'admin.story.category': 'Categoría',
    'admin.story.type': 'Tipo de Medio',
    'admin.story.author': 'Autor / Crédito',
    'admin.story.media': 'URL del Medio',
    'admin.story.cover': 'URL de la Portada',
    'admin.story.date': 'Fecha',
    'admin.success': 'Operación Exitosa',
    'admin.delete': 'Eliminar',
    'admin.delete_confirm': '¿Está seguro de que desea eliminar esto?',
    'admin.preview_mode': 'Modo de Vista Previa: Los cambios son locales y se restablecerán al actualizar.',

    // Common
    'common.loading': 'Cargando...',
    'common.back': 'Atrás',
    'common.submit': 'Enviar',
    'common.processing': 'Procesando...',
    'common.success': 'Éxito',
    'common.error': 'Error',
    'common.cancel': 'Cancelar',
    'common.save': 'Guardar Cambios',
    
    // Hero & Home General
    'hero.title': 'Amplificando las Voces de los Ignorados',
    'hero.subtitle': 'Utilizamos la narración documental para mostrar las experiencias vividas de falta de vivienda, adicción y dificultades.',
    'hero.badge': 'Registrando la Realidad',
    'hero.cta_stories': 'Ver Historias',
    'hero.cta_submit': 'Enviar Historia',
    'hero.cta_about': 'Conócenos',
    'hero.cta_donate': 'Donar Ahora',
    'hero.change_photo': 'Cambiar Foto',
    'hero.photo_source': 'Fuente de la foto',
    'hero.drop_zone': 'Arrastra la imagen para cambiar',

    // Impact Stats
    'home.impact.stories': 'Historias Contadas',
    'home.impact.helped': 'Personas Asistidas',
    'home.impact.verified_shelters': 'Refugios Verificados',
    'home.impact.partners': 'Agencias Vinculadas',
    'home.impact.volunteers': 'Miembros Activos',

    // News
    'home.news.title': 'Actualizaciones de la Crisis en California',
    'home.news.subtitle': 'Actualizaciones en vivo sobre política social.',
    'home.news.loading': 'Obteniendo las últimas actualizaciones...',
    'home.news.generated': 'Resumen de IA (Búsqueda en Google)',
    'home.news.sources': 'Fuentes Primarias',
    'home.news.error': 'No se pueden cargar las noticias.',

    // Methodology / Pillars
    'home.methodology.tag': 'Nuestra Metodología',
    'home.methodology.title': 'Uniendo Empatía y Acción',
    'home.pillar1.title': 'Periodismo Documental',
    'home.pillar1.desc': 'Revelando la verdad a través de imágenes crudas y sin filtrar.',
    'home.pillar2.title': 'Acción Inmediata',
    'home.pillar2.desc': 'Vinculando directamente las narrativas a más de 70 agencias verificadas.',
    'home.pillar3.title': 'Defensa de Políticas',
    'home.pillar3.desc': 'Impulsando el cambio sistémico con evidencia visual.',

    // Stories Page
    'stories.header.tag': 'Archivos Documentales',
    'stories.header.title': 'Historias de la Comunidad',
    'stories.header.sub': 'Narrativas auténticas capturadas por nuestros equipos para cerrar la brecha entre la empatía y la acción.',
    'stories.tab.video': 'Video',
    'stories.tab.photo': 'Foto',
    'stories.tab.audio': 'Podcast / Audio',
    'stories.filter.all': 'Todo',
    'stories.btn.submit': 'Comparte Tu Historia',
    'stories.empty': 'No se encontraron historias en esta categoría.',
    'stories.modal.resource_btn': 'Encontrar Recursos de Apoyo',

    // Submit Story Page
    'submit.title': 'Contribuir al Archivo',
    'submit.subtitle': 'Tu perspectiva importa. Sube fotos, videos o entrevistas de audio para documentar la realidad.',
    'submit.type.video_photo': 'Visual (Video/Foto)',
    'submit.type.audio': 'Audio (Podcast/Entrevista)',
    'submit.upload_photo': 'Subir Fotos',
    'submit.upload_video': 'Subir Video',
    'submit.upload_audio': 'Subir Archivo de Audio',
    'submit.upload_cover': 'Imagen de Portada (Opcional)',
    'submit.form.title': 'Título de la Historia',
    'submit.form.location': 'Ubicación (Ciudad/Calle)',
    'submit.form.category': 'Categoría',
    'submit.form.desc': 'La Narrativa',
    'submit.form.desc_placeholder': 'Describe el contexto, las personas y el momento...',
    'submit.terms': 'Certifico que tengo derecho a compartir este contenido y otorgo a Voice Through Image permiso para usarlo con fines educativos sin fines de lucro.',
    'submit.success_title': 'Narrativa Archivada',
    'submit.success_desc': 'Tu envío ha sido subido de forma segura a nuestra base de datos. Gracias por ser un testigo.',

    // Resources Page
    'resources.hero.tag': 'Asistente de Recursos IA',
    'resources.hero.title': '¿Cómo podemos ayudarte hoy?',
    'resources.hero.sub': 'Busca recursos utilizando lenguaje natural. Te conectaremos con servicios verificados.',
    'resources.search.placeholder': 'Ej: Necesito un lugar seguro para dormir en Los Ángeles...',
    'resources.search.btn': 'Buscar',
    'resources.prompt.shelter': 'Buscar Refugios',
    'resources.prompt.legal': 'Ayuda Legal',
    'resources.prompt.food': 'Comida Gratis',
    'resources.prompt.mental': 'Salud Mental',
    'resources.directory.title': 'Explorar Directorio',
    'resources.directory.sub': 'Selecciona una categoría para ver organizaciones verificadas.',
    'resources.directory.search_placeholder': 'Buscar por nombre, ciudad o servicio...',
    'resources.directory.view_all': 'Ver Todas las Categorías',
    'resources.ai_result': 'Respuesta del Asistente',
    'resources.close': 'Cerrar',

    // Resource Categories
    'resources.title': 'Recursos de Apoyo',
    'resources.subtitle': 'Encuentra apoyo local verificado.',
    'resources.cat.shelter': 'Refugios de Emergencia',
    'resources.cat.food': 'Bancos de Alimentos',
    'resources.cat.legal': 'Ayuda Legal',
    'resources.cat.mental_health': 'Salud Mental',
    'resources.cat.dv': 'Violencia Doméstica',
    'resources.cat.chinese_services': 'Apoyo en Chino',
    'resources.cat.recovery': 'Recuperación de Adicciones',

    // About Page
    'about.title': 'Nuestro Propósito Colectivo',
    'about.subtitle': 'Una plataforma documental sin fines de lucro que humaniza las crisis sociales a través del periodismo visual.',
    'about.tag': 'Nuestra Identidad Central',
    'about.vision_title': 'Visión y Legado',
    'about.vision_sub': 'NUESTRA VISIÓN',
    'about.vision_text': '"Cerrar la brecha entre la invisibilidad social y la empatía activa a través del poder de imágenes crudas y honestas."',
    'about.mission_sub': 'NUESTRA MISIÓN',
    'about.mission_1': 'Documentar la realidad sin adornos de la falta de vivienda y la adicción con dignidad.',
    'about.mission_2': 'Conectar a las personas marginadas con recursos inmediatos y culturalmente sensibles.',
    'about.mission_3': 'Impulsar el cambio de políticas sociales a través de la defensa visual basada en evidencia.',
    'about.participate.title': 'Cómo Puedes Participar',
    'about.participate.step1': 'Ser Testigo',
    'about.participate.step1_desc': 'Involúcrate con nuestras narrativas y comprende los problemas sistémicos.',
    'about.participate.step2': 'Unirse',
    'about.participate.step2_desc': 'Regístrate como voluntario o colaborador en tu ciudad local.',
    'about.participate.step3': 'Enviar',
    'about.participate.step3_desc': 'Ayúdanos a encontrar las historias que necesitan ser contadas.',
    'about.volunteer.title': 'Sé Voluntario',
    'about.volunteer.desc': 'Únete a nuestro compasivo equipo de documentalistas de campo, coordinadores de alcance y apoyo administrativo. Tu tiempo puede cambiar vidas.',
    'about.volunteer.roles': 'Roles: Documentación de Campo, Alcance Comunitario, Apoyo en Eventos, Servicios de Traducción.',
    'about.volunteer.btn': 'Regístrate como Voluntario',
    
    // Contact Page
    'contact.tag': 'Ponte en Contacto',
    'contact.title': 'Contáctanos',
    'contact.subtitle': 'Estamos aquí para escuchar, apoyar y colaborar. Comunícate con nuestro equipo.',
    'contact.office': 'Sede Central',
    'contact.email': 'Envíanos un Correo',
    'contact.phone': 'Llámanos',
    'contact.office_hours': 'Lun-Vie, 9am - 5pm PST',
    'contact.form.title': 'Enviar un Mensaje',
    'contact.form.name': 'Nombre Completo',
    'contact.form.email': 'Correo Electrónico',
    'contact.form.subject': 'Asunto',
    'contact.form.message': 'Mensaje',
    'contact.form.send': 'Enviar Mensaje',

    // Volunteer Page
    'volunteer.title': 'Únete a Nuestra Misión',
    'volunteer.subtitle': 'Presta tus habilidades para amplificar voces y apoyar nuestras operaciones comunitarias.',
    'volunteer.form.name': 'Nombre Completo',
    'volunteer.form.email': 'Correo Electrónico',
    'volunteer.form.phone': 'Número de Teléfono',
    'volunteer.form.role': 'Área de Interés',
    'volunteer.form.message': '¿Por qué quieres ser voluntario?',
    'volunteer.success': '¡Gracias! Tu solicitud ha sido recibida.',
    
    // Donate Page
    'donate.page.title': 'Financia la Misión',
    'donate.page.sub': 'Tu apoyo nos ayuda a permanecer en el terreno, ayudando personalmente a quienes lo necesitan y filmando historias que inspiran esperanza.',
    'donate.tiers.title': 'Acción Directa e Impacto Positivo',
    'donate.tier1.title': 'Documentación de Campo',
    'donate.tier1.desc': 'Necesitamos equipo para permanecer en el terreno, capturando historias auténticas de resiliencia. Estamos allí personalmente para presenciar y registrar la verdad.',
    'donate.tier2.title': 'Ayuda Comunitaria Práctica',
    'donate.tier2.desc': 'No solo observamos; actuamos. Entregamos personalmente suministros esenciales, coordinamos refugio y brindamos conexión humana a aquellos ignorados por la sociedad.',
    'donate.tier3.title': 'Historias de Esperanza',
    'donate.tier3.desc': 'Producimos documentales de alta calidad que se centran en el potencial humano y la transformación positiva, demostrando que todos merecen una segunda oportunidad.',
    'donate.secure': 'Pago Seguro vía Zeffy',
    'donate.fee_note': 'El 100% de tu donación va para nosotros. Zeffy cubre las tarifas.',
    'donate.check': 'Para donar con cheque o acciones, contáctanos.',
    'about.donate.title': 'Empodera la Narrativa',
    'about.donate.subtitle': 'Tu contribución nos permite producir documentales de alta calidad que impulsan un cambio real en las políticas.',
    'about.donate.tax': 'Las Donaciones son 100% Deducibles de Impuestos',
    'about.donate.btn': 'Donar Ahora',

    // NEW 20-SLIDE PRESENTATION
    'pres.s1.title': 'Voice Through Image',
    'pres.s1.sub': 'Una Plataforma Humanitaria Impulsada por Tecnología',
    'pres.s1.tag': 'Est. 2025',
    'pres.s2.title': 'La Desconexión',
    'pres.s2.text': 'Los Recursos Existen, la Conexión Falla',
    'pres.s2.sub': 'Fatiga por empatía + información dispersa = inacción.',
    'pres.s2.p1': 'Sistemas de Ayuda Fragmentados',
    'pres.s2.p2': '"Fatiga por Compasión" Pública',
    'pres.s2.p3': 'Sin Camino Claro para Ayudar',
    'pres.s3.title': 'Nuestra Filosofía Central',
    'pres.s3.vis': 'Acción Sobre Lástima',
    'pres.s3.mis': 'No filmamos "miseria" para generar culpa. Documentamos la realidad para desencadenar una intervención inmediata y tangible.',
    'pres.s4.title': 'El Ecosistema de Soluciones',
    'pres.s4.p1': 'Documental',
    'pres.s4.d1': 'Evidencia Visual',
    'pres.s4.p2': 'Plataforma IA',
    'pres.s4.d2': 'Integración Inteligente',
    'pres.s4.p3': 'Comunidad',
    'pres.s4.d3': 'Acción Directa',
    'pres.s5.title': 'Tecnología Avanzada',
    'pres.s5.stat': '24/7',
    'pres.s5.desc': 'Integración Gemini IA',
    'pres.s5.text': 'Nuestra plataforma utiliza Google Gemini IA para proporcionar emparejamiento de recursos en tiempo real, las 24 horas, para aquellos en crisis.',
    'pres.s6.title': 'El Centro Digital',
    'pres.s6.sub': 'Base de Datos de Recursos Unificada',
    'pres.s6.p1': '70+ Agencias Verificadas',
    'pres.s6.p2': 'Datos de Mapas en Vivo',
    'pres.s6.p3': 'Navegación Instantánea',
    'pres.s7.title': 'Narración Democratizada',
    'pres.s7.sub': 'Función de Carga Pública',
    'pres.s7.p1': 'Cualquiera Puede Contribuir',
    'pres.s7.p2': 'Verificado por el Equipo VTI',
    'pres.s7.p3': 'Voces desde el Terreno',
    'pres.s8.title': 'Viaje del Usuario',
    'pres.s8.steps': '1. Testigo de la Historia -> 2. Sentir Empatía -> 3. IA Empareja Recurso -> 4. Acción Directa',
    'pres.s9.title': 'Dignidad Primero',
    'pres.s9.text': 'Empoderamos a los sujetos para que cuenten sus PROPIAS historias.',
    'pres.s9.sub': 'Sin explotación. Solo empoderamiento.',
    'pres.s10.title': 'Métricas de Impacto',
    'pres.s10.stat1': '850+ Ayudados',
    'pres.s10.stat2': '120 Historias',
    'pres.s10.stat3': '45 Voluntarios',
    'pres.s11.title': 'Éxito Real',
    'pres.s11.quote': 'El bot de IA me encontró un refugio a las 3 AM cuando nadie más respondió.',
    'pres.s11.author': 'Sarah, Beneficiaria',
    'pres.s12.title': 'Ventaja Competitiva',
    'pres.s12.us': 'Modelo Tecnológico VTI',
    'pres.s12.others': 'Sin Fines de Lucro Tradicionales',
    'pres.s12.p1': 'Velocidad Impulsada por IA',
    'pres.s12.o1': 'Ingesta Manual Lenta',
    'pres.s12.p2': 'Transparencia Visual',
    'pres.s12.o2': 'Informes Anuales en PDF',
    'pres.s13.title': 'Pila Tecnológica',
    'pres.s13.stack': 'React + Firebase + Google Cloud AI',
    'pres.s13.desc': 'Construido para escala, velocidad y confiabilidad.',
    'pres.s14.title': 'Escalabilidad',
    'pres.s14.text': 'Nuestro modelo es agnóstico de la ciudad. Lanzamos en LA, luego nos expandimos globalmente.',
    'pres.s15.title': 'Transparencia Financiera',
    'pres.s15.sub': 'A dónde va la inversión',
    'pres.s15.p1': 'Desarrollo Tecnológico',
    'pres.s15.p2': 'Operaciones de Campo',
    'pres.s15.p3': 'Administración',
    'pres.s16.title': 'Hoja de Ruta 2026',
    'pres.s16.q1': 'Lanzamiento de App Móvil',
    'pres.s16.q2': 'Expansión a San Diego',
    'pres.s16.q3': 'Red Nacional de Socios',
    'pres.s17.title': 'Estado Oficial',
    'pres.s17.stat': '501(c)(3)',
    'pres.s17.text': 'Donaciones totalmente deducibles de impuestos. Certificado por el IRS.',
    'pres.s18.title': 'La Solicitud',
    'pres.s18.goal': '$500k',
    'pres.s18.sub': 'Financiamiento Semilla por 18 Meses',
    'pres.s18.items': 'Equipo de Desarrollo, Furgoneta, Equipo de Cámara, Personal de Alcance',
    'pres.s19.title': '¿Por Qué Ahora?',
    'pres.s19.text': 'La crisis está en su punto máximo. La tecnología está lista. Estamos listos.',
    'pres.s20.title': 'Únete al Movimiento',
    'pres.s20.sub': 'Invierte en Acción.',
    'pres.s20.cta': 'Donar / Asociarse',

    // Footer & Legal
    'about.history': 'Historia Corporativa',
    'about.history_text': 'Fundada a finales de 2025, Voice Through Image se estableció para contrarrestar la creciente "fatiga por compasión" en los principales centros urbanos.',
    'about.leadership': 'Liderazgo',
    'about.founder': 'FUNDADOR Y CEO',
    'about.roles': 'ROLES DE LA JUNTA',
    'about.roles_list': 'Cumplimiento Legal, Estrategia Narrativa, Alcance Comunitario.',
    'about.legal': 'Estado Sin Fines de Lucro',
    'about.legal_text': 'Voice Through Image es una organización exenta de impuestos registrada 501(c)(3). Las donaciones son deducibles de impuestos en la medida permitida por la ley.',
    'about.legal_ein': 'EIN FEDERAL',
    'footer.desc': 'Una plataforma documental sin fines de lucro dedicada a humanizar las crisis sociales.',
    'footer.ein': 'EIN: 41-2510011',
    'footer.tax_exempt': 'Determinado por el IRS 501(c)(3)',
    'footer.governance': 'Gobernanza',
    'footer.links.irs': 'Carta de Determinación del IRS',
    'footer.links.financial': 'Informes Financieros',
    'footer.links.bylaws': 'Estatutos y Políticas',
    'footer.links.deck': 'Ver Presentación Oficial',
    'footer.rights': 'Todos los Derechos Reservados.',
    'footer.privacy': 'Política de Privacidad',
    'footer.terms': 'Términos de Servicio',

    // Chat
    'chat.welcome': 'Bienvenido al Soporte de Voice Through Image. ¿Cómo puedo ayudarte hoy?',
    'chat.placeholder': 'Pregunta sobre recursos, nuestra misión, u obtén apoyo...',
    'chat.send': 'Enviar Mensaje',
    'chat.disclaimer': 'Soy un asistente de IA. Para emergencias, llama al 911 de inmediato.',
    'chat.error': 'Conexión perdida. Por favor intenta de nuevo más tarde.',
    
    // Auth
    'auth.login.title': 'Bienvenido de Nuevo',
    'auth.login.subtitle': 'Inicia sesión para acceder a tu cuenta',
    'auth.login.btn': 'Iniciar Sesión',
    'auth.signup.title': 'Crear Cuenta',
    'auth.signup.subtitle': 'Únete a nuestra comunidad de agentes de cambio',
    'auth.signup.btn': 'Crear Cuenta',
    'auth.verify.title': 'Verifica tu correo electrónico',
    'auth.verify.text': 'Enviamos un enlace de verificación a',
    'profile.title': 'Mi Perfil',
    'profile.manage': 'Administra la configuración de tu cuenta',
    'profile.edit': 'Editar Perfil',
    'profile.save': 'Guardar Cambios',
  }
};

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export const LanguageProvider: React.FC<{ children: ReactNode }> = ({ children }) => {
  const [language, setLanguage] = useState<Language>('zh-TW');
  const t = (key: string): string => {
      // Fallback for new keys if not present in other languages
      const langMap = translations[language];
      if (langMap && langMap[key]) return langMap[key];
      
      const enMap = translations['en'];
      if (enMap && enMap[key]) return enMap[key];
      
      return key;
  };

  const font = language === 'zh-CN' ? 'font-sc' : (language === 'zh-TW' ? 'font-tc' : 'font-serif');

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t, font }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (context === undefined) throw new Error('useLanguage must be used within a LanguageProvider');
  return context;
};
