
import React, { createContext, useContext, useState, ReactNode } from 'react';

export type Language = 'en' | 'zh-TW' | 'zh-CN' | 'es';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const translations: Record<Language, Record<string, string>> = {
  en: {
    'nav.home': 'Home',
    'nav.about': 'Our Mission',
    'nav.stories': 'Stories',
    'nav.resources': 'Resources',
    'nav.contact': 'Contact',
    'nav.chat': 'AI Support',
    'nav.login': 'Log in',
    'nav.join': 'Join Us',
    'nav.donate': 'Donate',
    'nav.profile': 'My Profile',
    'nav.signout': 'Sign Out',
    'hero.title': 'Amplifying Voices of the Overlooked',
    'hero.subtitle': 'We use documentary storytelling to surface lived experiences of homelessness, addiction, and hardship.',
    'hero.cta_stories': 'Watch Stories',
    'hero.cta_about': 'Learn About Us',
    'hero.cta_donate': 'Donate Now',
    'home.impact.stories': 'Stories Told',
    'home.impact.helped': 'People Assisted',
    'home.impact.partners': 'Agencies Linked',
    'home.impact.volunteers': 'Active Members',
    'home.news.title': 'California Crisis Updates',
    'home.news.subtitle': 'Live updates on social policy.',
    'home.news.loading': 'Fetching latest updates...',
    'home.news.generated': 'AI Summarized (Google Search)',
    'home.news.sources': 'Primary Sources',
    'home.news.error': 'Unable to load news.',
    'stories.title': 'Community Stories',
    'stories.subtitle': 'Authentic narratives captured by our teams.',
    'resources.title': 'Support Resources',
    'resources.subtitle': 'Find verified local support.',
    'resources.cat.shelter': 'Emergency Shelters',
    'resources.cat.food': 'Food Banks',
    'resources.cat.legal': 'Legal Aid',
    'resources.cat.mental_health': 'Mental Health',
    'resources.cat.dv': 'Domestic Violence',
    'resources.cat.chinese_services': 'Chinese Speaking Support',
    'resources.cat.recovery': 'Addiction Recovery',
    'about.title': 'Our Collective Purpose',
    'about.subtitle': 'A non-profit documentary platform humanizing social crises through visual journalism.',
    'about.vision_title': 'Vision & Legacy',
    'about.vision_sub': 'OUR VISION',
    'about.vision_text': '"To bridge the gap between social invisibility and active empathy through the power of raw, honest imagery."',
    'about.mission_sub': 'OUR MISSION',
    'about.mission_1': 'Document the unvarnished reality of homelessness and addiction with dignity.',
    'about.mission_2': 'Bridge marginalized individuals with immediate, culturally-sensitive resources.',
    'about.mission_3': 'Drive social policy change through evidence-based visual advocacy.',
    'about.participate.title': 'How You Can Participate',
    'about.participate.step1': 'Witness',
    'about.participate.step1_desc': 'Engage with our narratives and understand the systemic issues.',
    'about.participate.step2': 'Join',
    'about.participate.step2_desc': 'Register as a volunteer or contributor in your local city.',
    'about.participate.step3': 'Submit',
    'about.participate.step3_desc': 'Help us find the stories that need to be told.',
    'about.volunteer.title': 'Volunteer With Us',
    'about.volunteer.desc': 'Join our compassionate team of field documentarians, outreach coordinators, and administrative support. Your time can change lives.',
    'about.volunteer.roles': 'Roles: Field Documentation, Community Outreach, Event Support, Translation Services.',
    'about.volunteer.btn': 'Sign Up to Volunteer',
    'volunteer.title': 'Join Our Mission',
    'volunteer.subtitle': 'Lend your skills to amplify voices and support our community operations.',
    'volunteer.form.name': 'Full Name',
    'volunteer.form.email': 'Email Address',
    'volunteer.form.phone': 'Phone Number',
    'volunteer.form.role': 'Area of Interest',
    'volunteer.form.message': 'Why do you want to volunteer?',
    'volunteer.success': 'Thank you! Your application has been received.',
    'about.donate.title': 'Empower the Narrative',
    'about.donate.subtitle': 'Your contribution enables us to produce high-quality documentaries that drive real policy change.',
    'about.donate.tax': 'Donations are 100% Tax-Deductible',
    'about.donate.btn': 'Donate Now',
    'about.history': 'Corporate History',
    'about.history_text': 'Founded in late 2025, Voice Through Image was established to counter the rising "compassion fatigue" in major urban centers.',
    'about.leadership': 'Leadership',
    'about.founder': 'FOUNDER & CEO',
    'about.roles': 'BOARD ROLES',
    'about.roles_list': 'Legal Compliance, Narrative Strategy, Community Outreach.',
    'about.legal': 'Non-Profit Status',
    'about.legal_text': 'Voice Through Image is a registered 501(c)(3) tax-exempt organization. Donations are tax-deductible to the full extent of the law.',
    'about.legal_ein': 'FEDERAL EIN',
    'footer.desc': 'A non-profit documentary platform dedicated to humanizing social crises.',
    'footer.ein': 'EIN: 41-2510011',
    'footer.tax_exempt': 'IRS Determined 501(c)(3)',
    'chat.welcome': 'Welcome to Voice Through Image Support. How can I help you today?',
    'chat.placeholder': 'Ask about resources, our mission, or get support...',
    'chat.send': 'Send Message',
    'chat.disclaimer': 'I am an AI assistant. For emergencies, please call 911 immediately.',
    'chat.error': 'Connection lost. Please try again later.',

    // Donate Page
    'donate.page.title': 'Fund the Mission',
    'donate.page.sub': 'Your support directly funds documentary equipment, field operations, and resource connection services.',
    'donate.tiers.title': 'Where Your Money Goes',
    'donate.tier1.title': 'Field Equipment',
    'donate.tier1.desc': '$50 provides SD cards and storage for our documentarians.',
    'donate.tier2.title': 'Community Outreach',
    'donate.tier2.desc': '$100 supports one day of resource distribution in Skid Row.',
    'donate.tier3.title': 'Production Costs',
    'donate.tier3.desc': '$500 funds post-production for one short documentary.',
    'donate.secure': 'Secure Payment via Zeffy',
    'donate.fee_note': '100% of your donation goes to us. Zeffy covers the fees.',
    'donate.check': 'To donate by check or stock, please contact us.',
    
    // Presentation Deck (English)
    'pres.s1.title': 'Voice Through Image',
    'pres.s1.sub': 'Documenting Reality. Restoring Dignity.',
    'pres.s1.tag': '2026 Non-Profit Fundraising Deck',
    'pres.s2.title': 'The Cost of Silence',
    'pres.s2.text': 'A Moral Emergency',
    'pres.s2.p1': '580,000+ souls are screaming in silence on our streets.',
    'pres.s2.p2': 'Every day we look away, we lose a piece of our humanity.',
    'pres.s2.p3': 'Without documentation, their stories—and their lives—are erased.',
    'pres.s3.title': 'Our Core Mission',
    'pres.s3.vis': 'To ensure no story goes unheard, and no plea for help goes unanswered.',
    'pres.s3.mis': 'We are a 501(c)(3) non-profit battling the erasure of the marginalized through high-impact cinema and AI technology.',
    'pres.s4.title': 'The Three Pillars',
    'pres.s4.p1': 'Document',
    'pres.s4.d1': 'Professional, cinematic storytelling.',
    'pres.s4.p2': 'Connect',
    'pres.s4.d2': 'AI-driven resource matching.',
    'pres.s4.p3': 'Advocate',
    'pres.s4.d3': 'Data for policy change.',
    'pres.s5.title': 'Interview: "The Veteran"',
    'pres.s5.quote': '"I was a number in the system until someone asked me my name and turned on the camera. That was the first time I felt seen in years."',
    'pres.s5.author': '- James T., USMC Veteran, Skid Row',
    'pres.s6.title': 'Our Differentiation',
    'pres.s6.us': 'Voice Through Image',
    'pres.s6.others': 'Traditional Media',
    'pres.s6.p1': 'Action-Oriented Journalism',
    'pres.s6.p2': 'Direct Resource Linking',
    'pres.s6.p3': 'Non-Profit Integrity',
    'pres.s6.o1': 'Passive Observation',
    'pres.s6.o2': 'No Follow-up',
    'pres.s6.o3': 'Profit Driven',
    'pres.s7.title': 'The Ecosystem',
    'pres.s7.sub': 'We do not compete; We connect.',
    'pres.s7.p1': 'We partner with 70+ existing agencies (URM, Midnight Mission).',
    'pres.s7.p2': 'We act as the "Media Arm" for the entire social sector.',
    'pres.s8.title': 'Technology for Good',
    'pres.s8.stat': '24/7',
    'pres.s8.desc': 'AI Assistant Availability',
    'pres.s8.text': 'Our Gemini-powered directory breaks language barriers (EN/ZH/ES) instantly.',
    'pres.s9.title': 'Boots on the Ground',
    'pres.s9.sub': 'Our Volunteer Network',
    'pres.s9.p1': 'Field Videographers',
    'pres.s9.p2': 'Street Outreach Teams',
    'pres.s9.p3': 'Social Workers',
    'pres.s10.title': 'Success Story: Maria',
    'pres.s10.text': 'Found via our "Domestic Violence" portal. Connected to shelter in 2 hours. Now employed and housed.',
    'pres.s11.title': 'Financial Transparency',
    'pres.s11.sub': 'Every dollar is accounted for.',
    'pres.s11.p1': '85% Program Services',
    'pres.s11.p2': '10% Admin',
    'pres.s11.p3': '5% Fundraising',
    'pres.s12.title': 'Tax Deductibility',
    'pres.s12.stat': '501(c)(3)',
    'pres.s12.sub': 'IRS Certified Public Charity',
    'pres.s12.text': 'Your donations are 100% tax-deductible. We provide full documentation for your tax filings.',
    'pres.s13.title': 'The Roadmap 2026',
    'pres.s13.q1': 'Q1: Expand to San Francisco',
    'pres.s13.q2': 'Q2: Launch Mobile App',
    'pres.s13.q3': 'Q3: Federal Grant Partnership',
    'pres.s14.title': 'Silence is Complicity',
    'pres.s14.text': '"The ultimate tragedy is not the oppression and cruelty by the bad people but the silence over that by the good people."',
    'pres.s14.sub': 'We choose to speak. We choose to act. Join us.',
    'pres.s15.title': 'Strategic Capital Need',
    'pres.s15.goal': '$2.5M',
    'pres.s15.sub': 'Annual Impact Fund Allocation',
    'pres.s15.i1': 'Cinematic Equipment',
    'pres.s15.i2': 'Transportation & Logistics',
    'pres.s15.i3': 'Operational Expenses',
    'pres.s15.i4': 'Documentary Production',
    'pres.s15.i5': 'Podcast & Interviews',
    'pres.s15.i6': 'Care & Outreach',
    'pres.s15.i7': 'Agency Networking',
    'pres.s16.title': 'Your Legacy',
    'pres.s16.sub': 'Become an Honorary Board Member. Define the narrative of our generation.',
    'pres.s16.cta': 'Click to Donate',
  },
  'zh-TW': {
    'nav.home': '首頁',
    'nav.about': '我們的使命',
    'nav.stories': '故事',
    'nav.resources': '資源',
    'nav.contact': '聯絡我們',
    'nav.chat': 'AI 助手',
    'nav.login': '登入',
    'nav.join': '加入我們',
    'nav.donate': '捐款',
    'nav.profile': '個人檔案',
    'nav.signout': '登出',
    'hero.title': '放大被忽視的聲音',
    'hero.subtitle': '我們透過紀錄片敘事呈現真實經歷——將觀眾與實際支援連結起來。',
    'hero.cta_stories': '觀看故事',
    'hero.cta_about': '了解我們',
    'hero.cta_donate': '立即捐款',
    'home.impact.stories': '已說故事',
    'home.impact.helped': '已助人數',
    'home.impact.partners': '機構連結',
    'home.impact.volunteers': '活躍志工',
    'home.news.title': '加州危機動態',
    'home.news.subtitle': '社會政策的實時更新。',
    'home.news.loading': '正在獲取最新動態...',
    'home.news.generated': 'AI 智慧摘要 (Google Search)',
    'home.news.sources': '新聞來源',
    'home.news.error': '無法載入新聞。',
    'stories.title': '社區故事',
    'stories.subtitle': '由我們團隊捕捉的真實敘事。',
    'resources.title': '支援資源',
    'resources.subtitle': '搜尋經過驗證的在地支援。',
    'resources.cat.shelter': '緊急收容所',
    'resources.cat.food': '食物銀行',
    'resources.cat.legal': '法律援助',
    'resources.cat.mental_health': '心理健康',
    'resources.cat.dv': '家庭暴力',
    'resources.cat.chinese_services': '華語專項服務',
    'resources.cat.recovery': '藥物成癮康復',
    'about.title': '我們的使命',
    'about.subtitle': '透過視覺紀實，將社會危機人性化的非營利平台。',
    'about.vision_title': '願景與傳承',
    'about.vision_sub': '我們的願景',
    'about.vision_text': '「透過真實、誠實的影像力量，消除社會忽視與主動同理心之間的鴻溝。」',
    'about.mission_sub': '核心使命',
    'about.mission_1': '以尊嚴記錄無家可歸與成癮問題的真實現狀。',
    'about.mission_2': '為邊緣群體與即時的、具文化敏感性的資源建立橋樑。',
    'about.mission_3': '透過基於實證的視覺倡議，推動社會政策變革。',
    'about.participate.title': '如何參與',
    'about.participate.step1': '見證',
    'about.participate.step1_desc': '深入了解敘事，理解背後的系統性問題。',
    'about.participate.step2': '加入',
    'about.participate.step2_desc': '註冊成為志工，在您所在的城市貢獻力量。',
    'about.participate.step3': '提交',
    'about.participate.step3_desc': '幫助我們挖掘那些需要被聽見的故事。',
    'about.volunteer.title': '成為志工',
    'about.volunteer.desc': '加入我們充滿熱忱的團隊，包括田野紀實、社區外展及行政支援。您的時間可以改變生命。',
    'about.volunteer.roles': '角色：田野紀實、社區外展、活動支援、翻譯服務。',
    'about.volunteer.btn': '立即報名志工',
    'volunteer.title': '加入我們的使命',
    'volunteer.subtitle': '貢獻您的專長，放大被忽視的聲音並支援我們的社區運作。',
    'volunteer.form.name': '全名',
    'volunteer.form.email': '電子郵件',
    'volunteer.form.phone': '電話號碼',
    'volunteer.form.role': '感興趣的領域',
    'volunteer.form.message': '為什麼您想成為志工？',
    'volunteer.success': '感謝您！我們已收到您的申請。',
    'about.donate.title': '賦予敘事力量',
    'about.donate.subtitle': '您的捐款將直接支持我們製作推動政策改變的高品質紀錄片。',
    'about.donate.tax': '捐款可 100% 抵扣稅款',
    'about.donate.btn': '立即捐款',
    'about.history': '機構歷史',
    'about.history_text': '成立於 2025 年底，Voice Through Image 旨在應對大都市日益嚴重的「同理心疲勞」。',
    'about.leadership': '領導團隊',
    'about.founder': '創辦人與執行長',
    'about.roles': '董事職務',
    'about.roles_list': '法律合規、敘事策略、社區外展。',
    'about.legal': '非營利組織地位',
    'about.legal_text': 'Voice Through Image 是註冊的 501(c)(3) 免稅組織。捐款依法可抵扣稅款。',
    'about.legal_ein': '聯邦統編 EIN',
    'footer.desc': '致力於將當代社會危機人性化的非營利紀錄片平台。',
    'footer.ein': 'EIN 統編: 41-2510011',
    'footer.tax_exempt': 'IRS 認定 501(c)(3) 免稅機構',
    'chat.welcome': '歡迎來到 Voice Through Image 支援中心。請問今天有什麼我可以幫您的？',
    'chat.placeholder': '詢問資源、了解我們的使命，或尋求支持...',
    'chat.send': '發送訊息',
    'chat.disclaimer': '我是 AI 助手。如遇緊急危險情況，請立即撥打 911。',
    'chat.error': '連線中斷，請稍後再試。',

    // Donate Page
    'donate.page.title': '資助我們的使命',
    'donate.page.sub': '您的支持將直接資助紀錄片器材、田野行動及資源連結服務。',
    'donate.tiers.title': '您的資金去向',
    'donate.tier1.title': '田野器材',
    'donate.tier1.desc': '$50 可為我們的紀實團隊提供記憶卡與儲存設備。',
    'donate.tier2.title': '社區外展',
    'donate.tier2.desc': '$100 支持在 Skid Row 進行的一日物資發放與關懷。',
    'donate.tier3.title': '製作成本',
    'donate.tier3.desc': '$500 資助一部短紀錄片的後製剪輯工作。',
    'donate.secure': '透過 Zeffy 安全支付',
    'donate.fee_note': '您的捐款將 100% 交給我們。Zeffy 平台自行吸收手續費。',
    'donate.check': '如需透過支票或股票捐款，請聯繫我們。',

    // Presentation Deck (Traditional Chinese)
    'pres.s1.title': 'Voice Through Image',
    'pres.s1.sub': '紀錄真實。重塑尊嚴。',
    'pres.s1.tag': '2026 非營利組織募款計畫書',
    'pres.s2.title': '沈默的代價',
    'pres.s2.text': '道德的緊急狀態',
    'pres.s2.p1': '58 萬個靈魂正在我們的街道上無聲吶喊。',
    'pres.s2.p2': '每一天我們的視而不見，都在削弱我們的人性。',
    'pres.s2.p3': '如果沒有被記錄，他們的故事——以及生命——將被徹底抹去。',
    'pres.s3.title': '我們的核心使命',
    'pres.s3.vis': '確保沒有一個故事被遺忘，沒有一個求救被忽視。',
    'pres.s3.mis': '我們是 501(c)(3) 非營利組織，透過高影響力的影像新聞與 AI 科技，對抗邊緣族群的被抹除。',
    'pres.s4.title': '三大支柱',
    'pres.s4.p1': '紀實 (Document)',
    'pres.s4.d1': '專業、電影級的敘事。',
    'pres.s4.p2': '連結 (Connect)',
    'pres.s4.d2': 'AI 驅動的資源配對。',
    'pres.s4.p3': '倡導 (Advocate)',
    'pres.s4.d3': '以數據推動政策變革。',
    'pres.s5.title': '採訪實錄：「老兵」',
    'pres.s5.quote': '「直到有人問我的名字並打開攝影機，我才覺得自己重新被當作一個人看待。在這之前，我只是系統裡的一個數字。」',
    'pres.s5.author': '- James T., 前海軍陸戰隊，Skid Row',
    'pres.s6.title': '我們的獨特之處',
    'pres.s6.us': 'Voice Through Image',
    'pres.s6.others': '傳統媒體',
    'pres.s6.p1': '行動導向的新聞學',
    'pres.s6.p2': '直接資源連結',
    'pres.s6.p3': '非營利組織的誠信',
    'pres.s6.o1': '被動觀察',
    'pres.s6.o2': '無後續追蹤',
    'pres.s6.o3': '利潤導向',
    'pres.s7.title': '合作生態系',
    'pres.s7.sub': '我們不競爭；我們連結。',
    'pres.s7.p1': '我們與 70+ 現有機構合作 (如 URM, Midnight Mission)。',
    'pres.s7.p2': '我們扮演整個社會福利部門的「媒體手臂」。',
    'pres.s8.title': '科技向善',
    'pres.s8.stat': '24/7',
    'pres.s8.desc': 'AI 助手全天候待命',
    'pres.s8.text': '我們的 Gemini 驅動目錄即時打破語言障礙 (中/英/西)，讓資源唾手可得。',
    'pres.s9.title': '實際行動',
    'pres.s9.sub': '我們的志工網絡',
    'pres.s9.p1': '田野攝影師',
    'pres.s9.p2': '街頭外展團隊',
    'pres.s9.p3': '專業社工',
    'pres.s10.title': '成功案例：Maria',
    'pres.s10.text': '透過我們的「反家暴」入口網站被發現。2小時內連結至收容所。目前已就業並擁有穩定住所。',
    'pres.s11.title': '財務透明度',
    'pres.s11.sub': '每一分錢都有跡可循。',
    'pres.s11.p1': '85% 專案服務',
    'pres.s11.p2': '10% 行政管理',
    'pres.s11.p3': '5% 募款成本',
    'pres.s12.title': '稅務優勢',
    'pres.s12.stat': '501(c)(3)',
    'pres.s12.sub': 'IRS 認證公共慈善機構',
    'pres.s12.text': '您的捐款 100% 可抵扣稅款。我們將提供完整的稅務申報文件。',
    'pres.s13.title': '2026 發展藍圖',
    'pres.s13.q1': 'Q1: 擴展至舊金山',
    'pres.s13.q2': 'Q2: 發布行動 App',
    'pres.s13.q3': 'Q3: 聯邦補助合作',
    'pres.s14.title': '沈默即是共犯',
    'pres.s14.text': '「最大的悲劇不是壞人的壓迫與殘酷，而是好人對此的沈默。」',
    'pres.s14.sub': '我們選擇發聲，我們選擇行動。加入我們，打破沈默。',
    'pres.s15.title': '年度影響力基金',
    'pres.s15.goal': '$2.5M',
    'pres.s15.sub': '資金分配與運作',
    'pres.s15.i1': '專業器材與技術',
    'pres.s15.i2': '交通運輸與後勤',
    'pres.s15.i3': '日常營運開銷',
    'pres.s15.i4': '紀錄片製作',
    'pres.s15.i5': 'Podcast 與採訪',
    'pres.s15.i6': '社區關懷與物資',
    'pres.s15.i7': '連結其他機構',
    'pres.s16.title': '您的傳承',
    'pres.s16.sub': '成為榮譽董事。定義我們這個世代的敘事。',
    'pres.s16.cta': '點擊捐款',
  },
  'zh-CN': {
    'nav.home': '首页',
    'nav.about': '我们的使命',
    'nav.stories': '故事',
    'nav.resources': '资源',
    'nav.contact': '联系我们',
    'nav.chat': 'AI 助手',
    'nav.login': '登录',
    'nav.join': '加入我们',
    'nav.donate': '捐款',
    'nav.profile': '个人档案',
    'nav.signout': '登出',
    'hero.title': '放大被忽视的声音',
    'hero.subtitle': '我们通过纪录片叙事呈现真实经历——将观众与实际支援联系起来。',
    'hero.cta_stories': '观看故事',
    'hero.cta_about': '了解我们',
    'hero.cta_donate': '立即捐款',
    'home.impact.stories': '已说故事',
    'home.impact.helped': '已助人数',
    'home.impact.partners': '机构联系',
    'home.impact.volunteers': '活跃志愿者',
    'home.news.title': '加州危机动态',
    'home.news.subtitle': '社会政策的实时更新。',
    'home.news.loading': '正在获取最新动态...',
    'home.news.generated': 'AI 智慧摘要 (Google Search)',
    'home.news.sources': '新闻来源',
    'home.news.error': '无法加载新闻。',
    'stories.title': '社区故事',
    'stories.subtitle': '由我们团队捕捉的真实叙事。',
    'resources.title': '支援资源',
    'resources.subtitle': '搜索经过验证的在地支援。',
    'resources.cat.shelter': '紧急收容所',
    'resources.cat.food': '食物银行',
    'resources.cat.legal': '法律援助',
    'resources.cat.mental_health': '心理健康',
    'resources.cat.dv': '暴力',
    'resources.cat.chinese_services': '华语专项服务',
    'resources.cat.recovery': '药物成瘾康复',
    'about.title': '我们的使命',
    'about.subtitle': '通过视觉纪实，将社会危机人性化的非营利平台。',
    'about.vision_title': '愿景与传承',
    'about.vision_sub': '我们的愿景',
    'about.vision_text': '“通过真实、诚实的力量，消除社会忽视与主动同理心之间的鸿沟。”',
    'about.mission_sub': '核心使命',
    'about.mission_1': '以尊严记录无家可归与成瘾问题的真实现状。',
    'about.mission_2': '为边缘群体与即时的、具文化敏感性的资源建立桥梁。',
    'about.mission_3': '通过基于实证的视觉倡议，推动社会政策变革。',
    'about.participate.title': '如何参与',
    'about.participate.step1': '见证',
    'about.participate.step1_desc': '深入了解叙事，理解背后的系统性问题。',
    'about.participate.step2': '加入',
    'about.participate.step2_desc': '注册成为志愿者，在您所在的城市贡献力量。',
    'about.participate.step3': '提交',
    'about.participate.step3_desc': '帮助我们挖掘那些需要被听见的故事。',
    'about.volunteer.title': '成为志愿者',
    'about.volunteer.desc': '加入我们充满热忱的团队，包括田野纪实、社区外展及行政支援。您的时间可以改变生命。',
    'about.volunteer.roles': '角色：田野纪实、社区外展、活动支援、翻译服务。',
    'about.volunteer.btn': '立即报名志愿者',
    'volunteer.title': '加入我们的使命',
    'volunteer.subtitle': '贡献您的专长，放大被忽视的声音并支援我们的社区运作。',
    'volunteer.form.name': '全名',
    'volunteer.form.email': '电子邮件',
    'volunteer.form.phone': '电话号码',
    'volunteer.form.role': '感兴趣的领域',
    'volunteer.form.message': '为什么您想成为志愿者？',
    'volunteer.success': '感谢您！我们已收到您的申请。',
    'about.donate.title': '赋予叙事力量',
    'about.donate.subtitle': '您的捐款将直接支持我们制作推动政策改变的高品质纪录片。',
    'about.donate.tax': '捐款可 100% 抵扣税款',
    'about.donate.btn': '立即捐款',
    'about.history': '机构历史',
    'about.history_text': '成立于 2025 年底，Voice Through Image 旨在应对大都市日益严重的“同理心疲劳”。',
    'about.leadership': '领导团队',
    'about.founder': '创始人与首席执行官',
    'about.roles': '董事职务',
    'about.roles_list': '法律合规、叙事策略、社区外展。',
    'about.legal': '非营利组织地位',
    'about.legal_text': 'Voice Through Image 是注册的 501(c)(3) 免税组织。捐款依法可抵扣税款。',
    'about.legal_ein': '联邦统编 EIN',
    'footer.desc': '致力于将当代社会危机人性化的非营利纪录片平台。',
    'footer.ein': 'EIN 统编: 41-2510011',
    'footer.tax_exempt': 'IRS 认定 501(c)(3) 免稅機構',
    'chat.welcome': '欢迎来到 Voice Through Image 支援中心。请问今天有什么我可以帮您的？',
    'chat.placeholder': '询问资源、了解我们的使命，或寻求支持...',
    'chat.send': '发送信息',
    'chat.disclaimer': '我是 AI 助手。如遇紧急危险情况，请立即拨打 911。',
    'chat.error': '连接中断，请稍后再试。',
    
    // Donate Page
    'donate.page.title': '资助我们的使命',
    'donate.page.sub': '您的支持将直接资助纪录片器材、田野行动及资源链接服务。',
    'donate.tiers.title': '您的资金去向',
    'donate.tier1.title': '田野器材',
    'donate.tier1.desc': '$50 可为我们的纪实团队提供记忆卡与储存设备。',
    'donate.tier2.title': '社区外展',
    'donate.tier2.desc': '$100 支持在 Skid Row 进行的一日物资发放与关怀。',
    'donate.tier3.title': '制作成本',
    'donate.tier3.desc': '$500 资助一部短纪录片的后制剪辑工作。',
    'donate.secure': '通过 Zeffy 安全支付',
    'donate.fee_note': '您的捐款将 100% 交给我们。Zeffy 平台自行吸收手续费。',
    'donate.check': '如需通过支票或股票捐款，请联系我们。',

    // Presentation Deck (Simplified Chinese)
    'pres.s1.title': 'Voice Through Image',
    'pres.s1.sub': '纪录真实。重塑尊严。',
    'pres.s1.tag': '2026 非营利组织募款计划书',
    'pres.s2.title': '沉默的代价',
    'pres.s2.text': '道德的紧急状态',
    'pres.s2.p1': '58 万个灵魂正在我们的街道上无声呐喊。',
    'pres.s2.p2': '每一天我们的视而不见，都在削弱我们的人性。',
    'pres.s2.p3': '如果没有被记录，他们的故事——以及生命——将被彻底抹去。',
    'pres.s3.title': '我们的核心使命',
    'pres.s3.vis': '确保没有一个故事被遗忘，没有一个求救被忽视。',
    'pres.s3.mis': '我们是 501(c)(3) 非营利组织，通过高影响力的影像新闻与 AI 科技，对抗边缘族群的被抹除。',
    'pres.s4.title': '三大支柱',
    'pres.s4.p1': '纪实 (Document)',
    'pres.s4.d1': '专业、电影级的叙事。',
    'pres.s4.p2': '连结 (Connect)',
    'pres.s4.d2': 'AI 驱动的资源配对。',
    'pres.s4.p3': '倡导 (Advocate)',
    'pres.s4.d3': '以数据推动政策变革。',
    'pres.s5.title': '采访实录：“老兵”',
    'pres.s5.quote': '“直到有人问我的名字并打开摄影机，我才觉得自己重新被当作一个人看待。在这之前，我只是系统里的一个数字。”',
    'pres.s5.author': '- James T., 前海军陆战队，Skid Row',
    'pres.s6.title': '我们的独特之处',
    'pres.s6.us': 'Voice Through Image',
    'pres.s6.others': '传统媒体',
    'pres.s6.p1': '行动导向的新闻学',
    'pres.s6.p2': '直接资源连接',
    'pres.s6.p3': '非营利组织的诚信',
    'pres.s6.o1': '被动观察',
    'pres.s6.o2': '无后续追踪',
    'pres.s6.o3': '利润导向',
    'pres.s7.title': '合作生态系',
    'pres.s7.sub': '我们不竞争；我们连结。',
    'pres.s7.p1': '我们与 70+ 现有机构合作 (如 URM, Midnight Mission)。',
    'pres.s7.p2': '我们扮演整个社会福利部门的“媒体手臂”。',
    'pres.s8.title': '科技向善',
    'pres.s8.stat': '24/7',
    'pres.s8.desc': 'AI 助手全天候待命',
    'pres.s8.text': '我们的 Gemini 驱动目录即时打破语言障碍 (中/英/西)，让资源唾手可得。',
    'pres.s9.title': '实际行动',
    'pres.s9.sub': '我们的志愿者网络',
    'pres.s9.p1': '田野摄影师',
    'pres.s9.p2': '街头外展团队',
    'pres.s9.p3': '专业社工',
    'pres.s10.title': '成功案例：Maria',
    'pres.s10.text': '通过我们的“反家暴”入口网站被发现。2小时内连结至收容所。目前已就业并拥有稳定住所。',
    'pres.s11.title': '财务透明度',
    'pres.s11.sub': '每一分钱都有迹可循。',
    'pres.s11.p1': '85% 专案服务',
    'pres.s11.p2': '10% 行政管理',
    'pres.s11.p3': '5% 募款成本',
    'pres.s12.title': '税务优势',
    'pres.s12.stat': '501(c)(3)',
    'pres.s12.sub': 'IRS 认证公共慈善机构',
    'pres.s12.text': '您的捐款 100% 可抵扣税款。我们将提供完整的税务申报文件。',
    'pres.s13.title': '2026 发展蓝图',
    'pres.s13.q1': 'Q1: 扩展至旧金山',
    'pres.s13.q2': 'Q2: 发布移动 App',
    'pres.s13.q3': 'Q3: 联邦补助合作',
    'pres.s14.title': '沉默即是共犯',
    'pres.s14.text': '“最大的悲剧不是坏人的压迫与残酷，而是好人对此的沉默。”',
    'pres.s14.sub': '我们选择发声，我们选择行动。加入我们，打破沉默。',
    'pres.s15.title': '年度影响力基金',
    'pres.s15.goal': '$2.5M',
    'pres.s15.sub': '资金分配与运作',
    'pres.s15.i1': '专业器材与技术',
    'pres.s15.i2': '交通运输与后勤',
    'pres.s15.i3': '日常运营开销',
    'pres.s15.i4': '纪录片制作',
    'pres.s15.i5': 'Podcast 与采访',
    'pres.s15.i6': '社区关怀与物资',
    'pres.s15.i7': '链接其他机构',
    'pres.s16.title': '您的传承',
    'pres.s16.sub': '成为荣誉董事。定义我们这个世代的叙事。',
    'pres.s16.cta': '点击捐款',
  },
  'es': {
    'nav.home': 'Inicio',
    'nav.about': 'Misión',
    'nav.stories': 'Historias',
    'nav.resources': 'Recursos',
    'nav.contact': 'Contacto',
    'nav.chat': 'Soporte IA',
    'nav.login': 'Iniciar sesión',
    'nav.join': 'Únete',
    'nav.donate': 'Donar',
    'nav.profile': 'Perfil',
    'nav.signout': 'Cerrar sesión',
    'hero.title': 'Amplificando voces olvidadas',
    'hero.subtitle': 'Usamos el documental para visibilizar experiencias de falta de vivienda, adicción y dificultades.',
    'hero.cta_stories': 'Ver historias',
    'hero.cta_about': 'Conócenos',
    'hero.cta_donate': 'Donar Ahora',
    'home.impact.stories': 'Historias contadas',
    'home.impact.helped': 'Personas ayudadas',
    'home.impact.partners': 'Agencias conectadas',
    'home.impact.volunteers': 'Miembros activos',
    'home.news.title': 'Noticias de crisis en California',
    'home.news.subtitle': 'Actualizaciones en vivo sobre políticas sociales.',
    'home.news.loading': 'Cargando actualizaciones...',
    'home.news.generated': 'Resumen IA (Google Search)',
    'home.news.sources': 'Fuentes primarias',
    'home.news.error': 'No se pudieron cargar las noticias.',
    'stories.title': 'Historias comunitarias',
    'stories.subtitle': 'Narrativas auténticas capturadas por nuestros equipos.',
    'resources.title': 'Recursos de apoyo',
    'resources.subtitle': 'Encuentra apoyo local verificado.',
    'resources.cat.shelter': 'Refugios de emergencia',
    'resources.cat.food': 'Bancos de alimentos',
    'resources.cat.legal': 'Ayuda legal',
    'resources.cat.mental_health': 'Salud mental',
    'resources.cat.dv': 'Violencia doméstica',
    'resources.cat.chinese_services': 'Servicios en chino',
    'resources.cat.recovery': 'Recuperación de adicciones',
    'about.title': 'Nuestro propósito colectivo',
    'about.subtitle': 'Plataforma documental sin fines de lucro que humaniza crisis sociales.',
    'about.vision_title': 'Visión y Legado',
    'about.vision_sub': 'NUESTRA VISIÓN',
    'about.vision_text': '"Cerrar la brecha entre la invisibilidad social y la empatía activa mediante imágenes honestas."',
    'about.mission_sub': 'NUESTRA MISIÓN',
    'about.mission_1': 'Documentar la realidad de la falta de vivienda con dignidad.',
    'about.mission_2': 'Conectar individuos marginados con recursos inmediatos.',
    'about.mission_3': 'Impulsar cambios en políticas sociales mediante defensa visual.',
    'about.participate.title': 'Cómo participar',
    'about.participate.step1': 'Presenciar',
    'about.participate.step1_desc': 'Involúcrate con nuestras narrativas y entiende los problemas sistémicos.',
    'about.participate.step2': 'Unirse',
    'about.participate.step2_desc': 'Regístrate como voluntario en tu ciudad local.',
    'about.participate.step3': 'Enviar',
    'about.participate.step3_desc': 'Ayúdanos a encontrar las historias que necesitan ser contadas.',
    'about.volunteer.title': 'Voluntariado',
    'about.volunteer.desc': 'Únete a nuestro equipo compasivo de documentalistas de campo, coordinadores de divulgación y apoyo administrativo. Tu tiempo puede cambiar vidas.',
    'about.volunteer.roles': 'Roles: Documentación de campo, Divulgación comunitaria, Apoyo en eventos, Servicios de traducción.',
    'about.volunteer.btn': 'Regístrate para ser voluntario',
    'volunteer.title': 'Únete a nuestra misión',
    'volunteer.subtitle': 'Presta tus habilidades para amplificar voces y apoyar nuestras operaciones comunitarias.',
    'volunteer.form.name': 'Nombre completo',
    'volunteer.form.email': 'Dirección de correo electrónico',
    'volunteer.form.phone': 'Número de teléfono',
    'volunteer.form.role': 'Área de interés',
    'volunteer.form.message': '¿Por qué quieres ser voluntario?',
    'volunteer.success': '¡Gracias! Tu solicitud ha sido recibida.',
    'about.donate.title': 'Potencia la Narrativa',
    'about.donate.subtitle': 'Tu contribución nos permite producir documentales de alta calidad que impulsan cambios políticos reales.',
    'about.donate.tax': 'Donaciones 100% deducibles de impuestos',
    'about.donate.btn': 'Donar Ahora',
    'about.history': 'Historia corporativa',
    'about.history_text': 'Fundada en 2025 para contrarrestar la fatiga de compasión en centros urbanos.',
    'about.leadership': 'Liderazgo',
    'about.founder': 'FUNDADOR Y CEO',
    'about.roles': 'ROLES DE LA JUNTA',
    'about.roles_list': 'Cumplimiento legal, Estrategia narrativa, Alcance comunitario.',
    'about.legal': 'Estatus sin fines de lucro',
    'about.legal_text': 'Voice Through Image es una organización 501(c)(3) exenta de impuestos.',
    'about.legal_ein': 'EIN FEDERAL',
    'footer.desc': 'Plataforma dedicada a humanizar las crisis sociales.',
    'footer.ein': 'EIN: 41-2510011',
    'footer.tax_exempt': 'IRS Determinado 501(c)(3)',
    'chat.welcome': 'Bienvenido al soporte de Voice Through Image. ¿Cómo puedo ayudarte hoy?',
    'chat.placeholder': 'Pregunta sobre recursos, nuestra misión u obtén apoyo...',
    'chat.send': 'Enviar mensaje',
    'chat.disclaimer': 'Soy un asistente de IA. Para emergencias, llame al 911 de inmediato.',
    'chat.error': 'Conexión perdida. Inténtalo de nuevo más tarde.',
    
    // Donate Page
    'donate.page.title': 'Financiar la Misión',
    'donate.page.sub': 'Tu apoyo financia directamente equipos documentales, operaciones de campo y servicios de conexión de recursos.',
    'donate.tiers.title': 'A Dónde Va Tu Dinero',
    'donate.tier1.title': 'Equipo de Campo',
    'donate.tier1.desc': '$50 proporciona tarjetas SD y almacenamiento para nuestros documentalistas.',
    'donate.tier2.title': 'Alcance Comunitario',
    'donate.tier2.desc': '$100 apoya un día de distribución de recursos en Skid Row.',
    'donate.tier3.title': 'Costos de Producción',
    'donate.tier3.desc': '$500 financia la postproducción de un documental corto.',
    'donate.secure': 'Pago Seguro vía Zeffy',
    'donate.fee_note': 'El 100% de tu donación va para nosotros. Zeffy cubre las tarifas.',
    'donate.check': 'Para donar con cheque o acciones, contáctanos.',
    
    // Presentation Deck (Spanish)
    'pres.s1.title': 'Voice Through Image',
    'pres.s1.sub': 'Documentando la Realidad. Restaurando la Dignidad.',
    'pres.s1.tag': 'Propuesta de Recaudación 2026',
    'pres.s2.title': 'El Costo del Silencio',
    'pres.s2.text': 'Emergencia Moral',
    'pres.s2.p1': '580,000+ almas gritan en silencio en nuestras calles.',
    'pres.s2.p2': 'Cada día que miramos hacia otro lado, perdemos parte de nuestra humanidad.',
    'pres.s2.p3': 'Sin documentación, sus historias—y sus vidas—se borran.',
    'pres.s3.title': 'Nuestra Misión Central',
    'pres.s3.vis': 'Asegurar que ninguna historia quede sin ser escuchada y ninguna petición de ayuda sin respuesta.',
    'pres.s3.mis': 'Somos una organización 501(c)(3) dedicada a combatir el borrado de los marginados mediante cine de alto impacto y tecnología.',
    'pres.s4.title': 'Los Tres Pilares',
    'pres.s4.p1': 'Documentar',
    'pres.s4.d1': 'Narración cinematográfica profesional.',
    'pres.s4.p2': 'Conectar',
    'pres.s4.d2': 'Emparejamiento de recursos con IA.',
    'pres.s4.p3': 'Abogar',
    'pres.s4.d3': 'Datos para el cambio político.',
    'pres.s5.title': 'Entrevista: "El Veterano"',
    'pres.s5.quote': '"Fui un número en el sistema hasta que alguien me preguntó mi nombre y encendió la cámara. Fue la primera vez que me sentí visto en años."',
    'pres.s5.author': '- James T., Veterano USMC, Skid Row',
    'pres.s6.title': 'Nuestra Diferencia',
    'pres.s6.us': 'Voice Through Image',
    'pres.s6.others': 'Medios Tradicionales',
    'pres.s6.p1': 'Periodismo Orientado a la Acción',
    'pres.s6.p2': 'Enlace Directo de Recursos',
    'pres.s6.p3': 'Integridad Sin Fines de Lucro',
    'pres.s6.o1': 'Observación Pasiva',
    'pres.s6.o2': 'Sin Seguimiento',
    'pres.s6.o3': 'Impulsado por Beneficios',
    'pres.s7.title': 'El Ecosistema',
    'pres.s7.sub': 'No competimos; Conectamos.',
    'pres.s7.p1': 'Nos asociamos con +70 agencias existentes (URM, Midnight Mission).',
    'pres.s7.p2': 'Actuamos como el "Brazo Mediático" de todo el sector social.',
    'pres.s8.title': 'Tecnología para el Bien',
    'pres.s8.stat': '24/7',
    'pres.s8.desc': 'Disponibilidad Asistente IA',
    'pres.s8.text': 'Nuestro directorio Gemini rompe barreras lingüísticas (EN/ZH/ES) al instante.',
    'pres.s9.title': 'Acción en el Terreno',
    'pres.s9.sub': 'Nuestra Red de Voluntarios',
    'pres.s9.p1': 'Videógrafos de Campo',
    'pres.s9.p2': 'Equipos de Alcance',
    'pres.s9.p3': 'Trabajadores Sociales',
    'pres.s10.title': 'Historia de Éxito: Maria',
    'pres.s10.text': 'Encontrada a través de nuestro portal de "Violencia Doméstica". Conectada a refugio en 2 horas. Ahora empleada y alojada.',
    'pres.s11.title': 'Transparencia Financiera',
    'pres.s11.sub': 'Cada dólar está justificado.',
    'pres.s11.p1': '85% Servicios del Programa',
    'pres.s11.p2': '10% Administración',
    'pres.s11.p3': '5% Recaudación',
    'pres.s12.title': 'Deducibilidad Fiscal',
    'pres.s12.stat': '501(c)(3)',
    'pres.s12.sub': 'Caridad Pública Certificada por IRS',
    'pres.s12.text': 'Sus donaciones son 100% deducibles de impuestos. Proporcionamos documentación completa.',
    'pres.s13.title': 'Hoja de Ruta 2026',
    'pres.s13.q1': 'T1: Expansión a San Francisco',
    'pres.s13.q2': 'T2: Lanzamiento App Móvil',
    'pres.s13.q3': 'T3: Asociación de Subvención Federal',
    'pres.s14.title': 'El Silencio es Complicidad',
    'pres.s14.text': '"La tragedia final no es la opresión y crueldad de la gente mala, sino el silencio de la gente buena."',
    'pres.s14.sub': 'Elegimos hablar. Elegimos actuar. Únete a nosotros.',
    'pres.s15.title': 'Fondo de Impacto Anual',
    'pres.s15.goal': '$2.5M',
    'pres.s15.sub': 'Asignación de Fondos',
    'pres.s15.i1': 'Equipo Cinematográfico',
    'pres.s15.i2': 'Transporte y Logística',
    'pres.s15.i3': 'Gastos Operativos',
    'pres.s15.i4': 'Producción Documental',
    'pres.s15.i5': 'Podcasts y Entrevistas',
    'pres.s15.i6': 'Atención Comunitaria',
    'pres.s15.i7': 'Red de Agencias',
    'pres.s16.title': 'Tu Legado',
    'pres.s16.sub': 'Conviértete en Miembro Honorario de la Junta. Define la narrativa de nuestra generación.',
    'pres.s16.cta': 'Clic para Donar',
  }
};

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export const LanguageProvider: React.FC<{ children: ReactNode }> = ({ children }) => {
  const [language, setLanguage] = useState<Language>('zh-TW');
  const t = (key: string): string => translations[language]?.[key] || translations['en'][key] || key;

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (context === undefined) throw new Error('useLanguage must be used within a LanguageProvider');
  return context;
};
